const country = [
  {
    id: 1,
    name: 'Afghanistan',
    name_locale_id: 'Afghanistan',
    dial_code: '93',
    iso2: 'AF',
    iso3: 'AFG',
    denonym: 'Afghanistan',
    denonym_locale_id: 'Afghanistan',
    slug: 'afghanistan',
    slug_locale_id: 'afghanistan',
    denonym_slug: 'afghanistan',
    denonym_slug_locale_id: 'afghanistan'
  },
  {
    id: 245,
    name: 'Åland Islands',
    name_locale_id: 'Kepulauan Åland',
    dial_code: '358',
    iso2: 'AX',
    iso3: 'ALA',
    denonym: 'Åland Islands',
    denonym_locale_id: 'Kepulauan Åland',
    slug: 'aland-islands',
    slug_locale_id: 'kepulauan-aland',
    denonym_slug: 'aland-islands',
    denonym_slug_locale_id: 'kepulauan-aland'
  },
  {
    id: 2,
    name: 'Albania',
    name_locale_id: 'Albania',
    dial_code: '355',
    iso2: 'AL',
    iso3: 'ALB',
    denonym: 'Albania',
    denonym_locale_id: 'Albania',
    slug: 'albania',
    slug_locale_id: 'albania',
    denonym_slug: 'albania',
    denonym_slug_locale_id: 'albania'
  },
  {
    id: 3,
    name: 'Algeria',
    name_locale_id: 'Aljazair',
    dial_code: '213',
    iso2: 'DZ',
    iso3: 'DZA',
    denonym: 'Algeria',
    denonym_locale_id: 'Aljazair',
    slug: 'algeria',
    slug_locale_id: 'aljazair',
    denonym_slug: 'algeria',
    denonym_slug_locale_id: 'aljazair'
  },
  {
    id: 4,
    name: 'American Samoa',
    name_locale_id: 'Samoa Amerika',
    dial_code: '1-684',
    iso2: 'AS',
    iso3: 'ASM',
    denonym: 'American Samoa',
    denonym_locale_id: 'Samoa Amerika',
    slug: 'american-samoa',
    slug_locale_id: 'samoa-amerika',
    denonym_slug: 'american-samoa',
    denonym_slug_locale_id: 'samoa-amerika'
  },
  {
    id: 5,
    name: 'Andorra',
    name_locale_id: 'Andorra',
    dial_code: '376',
    iso2: 'AD',
    iso3: 'AND',
    denonym: 'Andorra',
    denonym_locale_id: 'Andorra',
    slug: 'andorra',
    slug_locale_id: 'andorra',
    denonym_slug: 'andorra',
    denonym_slug_locale_id: 'andorra'
  },
  {
    id: 6,
    name: 'Angola',
    name_locale_id: 'Angola',
    dial_code: '244',
    iso2: 'AO',
    iso3: 'AGO',
    denonym: 'Angola',
    denonym_locale_id: 'Angola',
    slug: 'angola',
    slug_locale_id: 'angola',
    denonym_slug: 'angola',
    denonym_slug_locale_id: 'angola'
  },
  {
    id: 7,
    name: 'Anguilla',
    name_locale_id: 'Anguilla',
    dial_code: '1-264',
    iso2: 'AI',
    iso3: 'AIA',
    denonym: 'Anguilla',
    denonym_locale_id: 'Anguilla',
    slug: 'anguilla',
    slug_locale_id: 'anguilla',
    denonym_slug: 'anguilla',
    denonym_slug_locale_id: 'anguilla'
  },
  {
    id: 8,
    name: 'Antigua and Barbuda',
    name_locale_id: 'Antigua dan Barbuda',
    dial_code: '1-268',
    iso2: 'AG',
    iso3: 'ATG',
    denonym: 'Antigua and Barbuda',
    denonym_locale_id: 'Antigua dan Barbuda',
    slug: 'antigua-and-barbuda',
    slug_locale_id: 'antigua-dan-barbuda',
    denonym_slug: 'antigua-and-barbuda',
    denonym_slug_locale_id: 'antigua-dan-barbuda'
  },
  {
    id: 9,
    name: 'Argentina',
    name_locale_id: 'Argentina',
    dial_code: '54',
    iso2: 'AR',
    iso3: 'ARG',
    denonym: 'Argentina',
    denonym_locale_id: 'Argentina',
    slug: 'argentina',
    slug_locale_id: 'argentina',
    denonym_slug: 'argentina',
    denonym_slug_locale_id: 'argentina'
  },
  {
    id: 10,
    name: 'Armenia',
    name_locale_id: 'Armenia',
    dial_code: '374',
    iso2: 'AM',
    iso3: 'ARM',
    denonym: 'Armenia',
    denonym_locale_id: 'Armenia',
    slug: 'armenia',
    slug_locale_id: 'armenia',
    denonym_slug: 'armenia',
    denonym_slug_locale_id: 'armenia'
  },
  {
    id: 11,
    name: 'Aruba',
    name_locale_id: 'Aruba',
    dial_code: '297',
    iso2: 'AW',
    iso3: 'ABW',
    denonym: 'Aruba',
    denonym_locale_id: 'Aruba',
    slug: 'aruba',
    slug_locale_id: 'aruba',
    denonym_slug: 'aruba',
    denonym_slug_locale_id: 'aruba'
  },
  {
    id: 12,
    name: 'Australia',
    name_locale_id: 'Australia',
    dial_code: '61',
    iso2: 'AU',
    iso3: 'AUS',
    denonym: 'Australia',
    denonym_locale_id: 'Australia',
    slug: 'australia',
    slug_locale_id: 'australia',
    denonym_slug: 'australia',
    denonym_slug_locale_id: 'australia'
  },
  {
    id: 13,
    name: 'Austria',
    name_locale_id: 'Austria',
    dial_code: '43',
    iso2: 'AT',
    iso3: 'AUT',
    denonym: 'Austria',
    denonym_locale_id: 'Austria',
    slug: 'austria',
    slug_locale_id: 'austria',
    denonym_slug: 'austria',
    denonym_slug_locale_id: 'austria'
  },
  {
    id: 14,
    name: 'Azerbaijan',
    name_locale_id: 'Azerbaijan',
    dial_code: '994',
    iso2: 'AZ',
    iso3: 'AZE',
    denonym: 'Azerbaijan',
    denonym_locale_id: 'Azerbaijan',
    slug: 'azerbaijan',
    slug_locale_id: 'azerbaijan',
    denonym_slug: 'azerbaijan',
    denonym_slug_locale_id: 'azerbaijan'
  },
  {
    id: 16,
    name: 'Bahrain',
    name_locale_id: 'Bahrain',
    dial_code: '973',
    iso2: 'BH',
    iso3: 'BHR',
    denonym: 'Bahrain',
    denonym_locale_id: 'Bahrain',
    slug: 'bahrain',
    slug_locale_id: 'bahrain',
    denonym_slug: 'bahrain',
    denonym_slug_locale_id: 'bahrain'
  },
  {
    id: 17,
    name: 'Bangladesh',
    name_locale_id: 'Bangladesh',
    dial_code: '880',
    iso2: 'BD',
    iso3: 'BGD',
    denonym: 'Bangladesh',
    denonym_locale_id: 'Bangladesh',
    slug: 'bangladesh',
    slug_locale_id: 'bangladesh',
    denonym_slug: 'bangladesh',
    denonym_slug_locale_id: 'bangladesh'
  },
  {
    id: 18,
    name: 'Barbados',
    name_locale_id: 'Barbados',
    dial_code: '1-246',
    iso2: 'BB',
    iso3: 'BRB',
    denonym: 'Barbados',
    denonym_locale_id: 'Barbados',
    slug: 'barbados',
    slug_locale_id: 'barbados',
    denonym_slug: 'barbados',
    denonym_slug_locale_id: 'barbados'
  },
  {
    id: 19,
    name: 'Belarus',
    name_locale_id: 'Belarus',
    dial_code: '375',
    iso2: 'BY',
    iso3: 'BLR',
    denonym: 'Belarus',
    denonym_locale_id: 'Belarus',
    slug: 'belarus',
    slug_locale_id: 'belarus',
    denonym_slug: 'belarus',
    denonym_slug_locale_id: 'belarus'
  },
  {
    id: 20,
    name: 'Belgium',
    name_locale_id: 'Belgia',
    dial_code: '32',
    iso2: 'BE',
    iso3: 'BEL',
    denonym: 'Belgium',
    denonym_locale_id: 'Belgia',
    slug: 'belgian',
    slug_locale_id: 'belgia',
    denonym_slug: 'belgian',
    denonym_slug_locale_id: 'belgia'
  },
  {
    id: 21,
    name: 'Belize',
    name_locale_id: 'Belize',
    dial_code: '501',
    iso2: 'BZ',
    iso3: 'BLZ',
    denonym: 'Belize',
    denonym_locale_id: 'Belize',
    slug: 'belize',
    slug_locale_id: 'belize',
    denonym_slug: 'belize',
    denonym_slug_locale_id: 'belize'
  },
  {
    id: 22,
    name: 'Benin',
    name_locale_id: 'Benin',
    dial_code: '229',
    iso2: 'BJ',
    iso3: 'BEN',
    denonym: 'Benin',
    denonym_locale_id: 'Benin',
    slug: 'benin',
    slug_locale_id: 'benin',
    denonym_slug: 'benin',
    denonym_slug_locale_id: 'benin'
  },
  {
    id: 23,
    name: 'Bermuda',
    name_locale_id: 'Bermuda',
    dial_code: '1-441',
    iso2: 'BM',
    iso3: 'BMU',
    denonym: 'Bermuda',
    denonym_locale_id: 'Bermuda',
    slug: 'bermuda',
    slug_locale_id: 'bermuda',
    denonym_slug: 'bermuda',
    denonym_slug_locale_id: 'bermuda'
  },
  {
    id: 24,
    name: 'Bhutan',
    name_locale_id: 'Bhutan',
    dial_code: '975',
    iso2: 'BT',
    iso3: 'BTN',
    denonym: 'Bhutan',
    denonym_locale_id: 'Bhutan',
    slug: 'bhutan',
    slug_locale_id: 'bhutan',
    denonym_slug: 'bhutan',
    denonym_slug_locale_id: 'bhutan'
  },
  {
    id: 25,
    name: 'Bolivia',
    name_locale_id: 'Bolivia',
    dial_code: '591',
    iso2: 'BO',
    iso3: 'BOL',
    denonym: 'Bolivia',
    denonym_locale_id: 'Bolivia',
    slug: 'bolivia',
    slug_locale_id: 'bolivia',
    denonym_slug: 'bolivia',
    denonym_slug_locale_id: 'bolivia'
  },
  {
    id: 26,
    name: 'Bonaire, Sint Eustatius and Saba',
    name_locale_id: 'Bonaire, Sint Eustasius dan Saba',
    dial_code: '599',
    iso2: 'BQ',
    iso3: 'BES',
    denonym: 'Bonaire, Sint Eustatius and Saba',
    denonym_locale_id: 'Bonaire, Sint Eustasius dan Saba',
    slug: 'bonaire-sint-eustasius-and-saba',
    slug_locale_id: 'bonaire-sint-eustasius-dan-saba',
    denonym_slug: 'bonaire-sint-eustasius-and-saba',
    denonym_slug_locale_id: 'bonaire-sint-eustasius-dan-saba'
  },
  {
    id: 27,
    name: 'Bosnia and Herzegovina',
    name_locale_id: 'Bosnia dan Herzegovina',
    dial_code: '387',
    iso2: 'BA',
    iso3: 'BIH',
    denonym: 'Bosnia and Herzegovina',
    denonym_locale_id: 'Bosnia dan Herzegovina',
    slug: 'bosnia-and-herzegovina',
    slug_locale_id: 'bosnia-dan-herzegovina',
    denonym_slug: 'bosnia-and-herzegovina',
    denonym_slug_locale_id: 'bosnia-dan-herzegovina'
  },
  {
    id: 28,
    name: 'Botswana',
    name_locale_id: 'Botswana',
    dial_code: '267',
    iso2: 'BW',
    iso3: 'BWA',
    denonym: 'Botswana',
    denonym_locale_id: 'Botswana',
    slug: 'botswana',
    slug_locale_id: 'botswana',
    denonym_slug: 'botswana',
    denonym_slug_locale_id: 'botswana'
  },
  {
    id: 29,
    name: 'Bouvet Island',
    name_locale_id: 'Pulau Bouvet',
    dial_code: '47',
    iso2: 'BV',
    iso3: 'BVT',
    denonym: 'Bouvet Island',
    denonym_locale_id: 'Pulau Bouvet',
    slug: 'bouvet-island',
    slug_locale_id: 'pulau-bouvet',
    denonym_slug: 'bouvet-island',
    denonym_slug_locale_id: 'pulau-bouvet'
  },
  {
    id: 30,
    name: 'Brazil',
    name_locale_id: 'Brasil',
    dial_code: '55',
    iso2: 'BR',
    iso3: 'BRA',
    denonym: 'Brazil',
    denonym_locale_id: 'Brasil',
    slug: 'brazil',
    slug_locale_id: 'brasil',
    denonym_slug: 'brazil',
    denonym_slug_locale_id: 'brasil'
  },
  {
    id: 31,
    name: 'British Indian Ocean Territory',
    name_locale_id: 'Wilayah Samudra Hindia Britania',
    dial_code: '246',
    iso2: 'IO',
    iso3: 'IOT',
    denonym: 'British Indian Ocean Territory',
    denonym_locale_id: 'Wilayah Samudra Hindia Britania',
    slug: 'british-indian-ocean-territory',
    slug_locale_id: 'wilayah-samudra-hindia-britania',
    denonym_slug: 'british-indian-ocean-territory',
    denonym_slug_locale_id: 'wilayah-samudra-hindia-britania'
  },
  {
    id: 32,
    name: 'British Virgin Islands',
    name_locale_id: 'Kepulauan Virgin Britania',
    dial_code: '1-284',
    iso2: 'VG',
    iso3: 'VGB',
    denonym: 'British Virgin Islands',
    denonym_locale_id: 'Kepulauan Virgin Britania',
    slug: 'british-virgin-islands',
    slug_locale_id: 'kepulauan-virgin-britania',
    denonym_slug: 'british-virgin-islands',
    denonym_slug_locale_id: 'kepulauan-virgin-britania'
  },
  {
    id: 33,
    name: 'Brunei',
    name_locale_id: 'Brunei',
    dial_code: '673',
    iso2: 'BN',
    iso3: 'BRN',
    denonym: 'Brunei',
    denonym_locale_id: 'Brunei',
    slug: 'brunei',
    slug_locale_id: 'brunei',
    denonym_slug: 'brunei',
    denonym_slug_locale_id: 'brunei'
  },
  {
    id: 34,
    name: 'Bulgaria',
    name_locale_id: 'Bulgaria',
    dial_code: '359',
    iso2: 'BG',
    iso3: 'BGR',
    denonym: 'Bulgaria',
    denonym_locale_id: 'Bulgaria',
    slug: 'bulgaria',
    slug_locale_id: 'bulgaria',
    denonym_slug: 'bulgaria',
    denonym_slug_locale_id: 'bulgaria'
  },
  {
    id: 35,
    name: 'Burkina Faso',
    name_locale_id: 'Burkina Faso',
    dial_code: '226',
    iso2: 'BF',
    iso3: 'BFA',
    denonym: 'Burkina Faso',
    denonym_locale_id: 'Burkina Faso',
    slug: 'burkina-faso',
    slug_locale_id: 'burkina-faso',
    denonym_slug: 'burkina-faso',
    denonym_slug_locale_id: 'burkina-faso'
  },
  {
    id: 36,
    name: 'Burundi',
    name_locale_id: 'Burundi',
    dial_code: '257',
    iso2: 'BI',
    iso3: 'BDI',
    denonym: 'Burundi',
    denonym_locale_id: 'Burundi',
    slug: 'burundi',
    slug_locale_id: 'burundi',
    denonym_slug: 'burundi',
    denonym_slug_locale_id: 'burundi'
  },
  {
    id: 37,
    name: 'Cabo Verde',
    name_locale_id: 'Tanjung Verde',
    dial_code: '238',
    iso2: 'CV',
    iso3: 'CPV',
    denonym: 'Cabo Verde',
    denonym_locale_id: 'Tanjung Verde',
    slug: 'cabo-verde',
    slug_locale_id: 'tanjung-verde',
    denonym_slug: 'cabo-verde',
    denonym_slug_locale_id: 'tanjung-verde'
  },
  {
    id: 38,
    name: 'Cambodia',
    name_locale_id: 'Kamboja',
    dial_code: '855',
    iso2: 'KH',
    iso3: 'KHM',
    denonym: 'Cambodia',
    denonym_locale_id: 'Kamboja',
    slug: 'cambodia',
    slug_locale_id: 'kamboja',
    denonym_slug: 'cambodia',
    denonym_slug_locale_id: 'kamboja'
  },
  {
    id: 39,
    name: 'Cameroon',
    name_locale_id: 'Kamerun',
    dial_code: '237',
    iso2: 'CM',
    iso3: 'CMR',
    denonym: 'Cameroon',
    denonym_locale_id: 'Kamerun',
    slug: 'cameroon',
    slug_locale_id: 'kamerun',
    denonym_slug: 'cameroon',
    denonym_slug_locale_id: 'kamerun'
  },
  {
    id: 40,
    name: 'Canada',
    name_locale_id: 'Kanada',
    dial_code: '1',
    iso2: 'CA',
    iso3: 'CAN',
    denonym: 'Canada',
    denonym_locale_id: 'Kanada',
    slug: 'canada',
    slug_locale_id: 'kanada',
    denonym_slug: 'canada',
    denonym_slug_locale_id: 'kanada'
  },
  {
    id: 41,
    name: 'Cayman Islands',
    name_locale_id: 'Kepulauan Cayman',
    dial_code: '1-345',
    iso2: 'KY',
    iso3: 'CYM',
    denonym: 'Cayman Islands',
    denonym_locale_id: 'Kepulauan Cayman',
    slug: 'cayman-islands',
    slug_locale_id: 'kepulauan-cayman',
    denonym_slug: 'cayman-islands',
    denonym_slug_locale_id: 'kepulauan-cayman'
  },
  {
    id: 42,
    name: 'Central African Republic',
    name_locale_id: 'Republik Afrika Tengah',
    dial_code: '236',
    iso2: 'CF',
    iso3: 'CAF',
    denonym: 'Central African Republic',
    denonym_locale_id: 'Republik Afrika Tengah',
    slug: 'central-african-republic',
    slug_locale_id: 'republik-afrika-tengah',
    denonym_slug: 'central-african-republic',
    denonym_slug_locale_id: 'republik-afrika-tengah'
  },
  {
    id: 43,
    name: 'Chad',
    name_locale_id: 'Chad',
    dial_code: '235',
    iso2: 'TD',
    iso3: 'TCD',
    denonym: 'Chad',
    denonym_locale_id: 'Chad',
    slug: 'chad',
    slug_locale_id: 'chad',
    denonym_slug: 'chad',
    denonym_slug_locale_id: 'chad'
  },
  {
    id: 44,
    name: 'Chile',
    name_locale_id: 'Chili',
    dial_code: '56',
    iso2: 'CL',
    iso3: 'CHL',
    denonym: 'Chile',
    denonym_locale_id: 'Chili',
    slug: 'chile',
    slug_locale_id: 'chili',
    denonym_slug: 'chile',
    denonym_slug_locale_id: 'chili'
  },
  {
    id: 45,
    name: 'China',
    name_locale_id: 'China',
    dial_code: '86',
    iso2: 'CN',
    iso3: 'CHN',
    denonym: 'China',
    denonym_locale_id: 'China',
    slug: 'china',
    slug_locale_id: 'china',
    denonym_slug: 'china',
    denonym_slug_locale_id: 'china'
  },
  {
    id: 48,
    name: 'Christmas Island',
    name_locale_id: 'Pulau Christmas',
    dial_code: '61',
    iso2: 'CX',
    iso3: 'CXR',
    denonym: 'Christmas Island',
    denonym_locale_id: 'Pulau Christmas',
    slug: 'christmas-island',
    slug_locale_id: 'pulau-christmas',
    denonym_slug: 'christmas-island',
    denonym_slug_locale_id: 'pulau-christmas'
  },
  {
    id: 49,
    name: 'Cocos (Keeling) Islands',
    name_locale_id: 'Kepulauan Cocos (Keeling)',
    dial_code: '61',
    iso2: 'CC',
    iso3: 'CCK',
    denonym: 'Cocos (Keeling) Islands',
    denonym_locale_id: 'Kepulauan Cocos (Keeling)',
    slug: 'cocos-keeling-islands',
    slug_locale_id: 'kepulauan-cocos-keeling',
    denonym_slug: 'cocos-keeling-islands',
    denonym_slug_locale_id: 'kepulauan-cocos-keeling'
  },
  {
    id: 50,
    name: 'Colombia',
    name_locale_id: 'Kolombia',
    dial_code: '57',
    iso2: 'CO',
    iso3: 'COL',
    denonym: 'Colombia',
    denonym_locale_id: 'Kolombia',
    slug: 'colombia',
    slug_locale_id: 'kolombia',
    denonym_slug: 'colombia',
    denonym_slug_locale_id: 'kolombia'
  },
  {
    id: 51,
    name: 'Comoros',
    name_locale_id: 'Komoro',
    dial_code: '269',
    iso2: 'KM',
    iso3: 'COM',
    denonym: 'Comoros',
    denonym_locale_id: 'Komoro',
    slug: 'comoros',
    slug_locale_id: 'komoro',
    denonym_slug: 'comoros',
    denonym_slug_locale_id: 'komoro'
  },
  {
    id: 62,
    name: 'Congo, Democratic Republic of the',
    name_locale_id: 'Republik Demokratik Kongo',
    dial_code: '243',
    iso2: 'CD',
    iso3: 'COD',
    denonym: 'Congo, Democratic Republic of the',
    denonym_locale_id: 'Republik Demokratik Kongo',
    slug: 'democratic-republic-of-the-congo',
    slug_locale_id: 'republik-demokratik-kongo',
    denonym_slug: 'democratic-republic-of-the-congo',
    denonym_slug_locale_id: 'republik-demokratik-kongo'
  },
  {
    id: 52,
    name: 'Congo, Republic of the',
    name_locale_id: 'Republik Kongo',
    dial_code: '242',
    iso2: 'CG',
    iso3: 'COG',
    denonym: 'Congo, Republic of the',
    denonym_locale_id: 'Republik Kongo',
    slug: 'republic-of-the-congo',
    slug_locale_id: 'republik-kongo',
    denonym_slug: 'republic-of-the-congo',
    denonym_slug_locale_id: 'republik-kongo'
  },
  {
    id: 53,
    name: 'Cook Islands',
    name_locale_id: 'Kepulauan Cook',
    dial_code: '682',
    iso2: 'CK',
    iso3: 'COK',
    denonym: 'Cook Islands',
    denonym_locale_id: 'Kepulauan Cook',
    slug: 'cook-islands',
    slug_locale_id: 'kepulauan-cook',
    denonym_slug: 'cook-islands',
    denonym_slug_locale_id: 'kepulauan-cook'
  },
  {
    id: 54,
    name: 'Costa Rica',
    name_locale_id: 'Kosta Rika',
    dial_code: '506',
    iso2: 'CR',
    iso3: 'CRI',
    denonym: 'Costa Rica',
    denonym_locale_id: 'Kosta Rika',
    slug: 'costa-rica',
    slug_locale_id: 'kosta-rika',
    denonym_slug: 'costa-rica',
    denonym_slug_locale_id: 'kosta-rika'
  },
  {
    id: 60,
    name: 'Côte d’Ivoire',
    name_locale_id: 'Pantai Gading',
    dial_code: '225',
    iso2: 'CI',
    iso3: 'CIV',
    denonym: 'Côte d’Ivoire',
    denonym_locale_id: 'Pantai Gading',
    slug: 'cote-d-ivoire',
    slug_locale_id: 'pantai-gading',
    denonym_slug: 'cote-d-ivoire',
    denonym_slug_locale_id: 'pantai-gading'
  },
  {
    id: 55,
    name: 'Croatia',
    name_locale_id: 'Kroasia',
    dial_code: '385',
    iso2: 'HR',
    iso3: 'HRV',
    denonym: 'Croatia',
    denonym_locale_id: 'Kroasia',
    slug: 'croatia',
    slug_locale_id: 'kroasia',
    denonym_slug: 'croatia',
    denonym_slug_locale_id: 'kroasia'
  },
  {
    id: 56,
    name: 'Cuba',
    name_locale_id: 'Kuba',
    dial_code: '53',
    iso2: 'CU',
    iso3: 'CUB',
    denonym: 'Cuba',
    denonym_locale_id: 'Kuba',
    slug: 'cuba',
    slug_locale_id: 'kuba',
    denonym_slug: 'cuba',
    denonym_slug_locale_id: 'kuba'
  },
  {
    id: 57,
    name: 'Curaçao',
    name_locale_id: 'Curacao',
    dial_code: '599',
    iso2: 'CW',
    iso3: 'CUW',
    denonym: 'Curaçao',
    denonym_locale_id: 'Curacao',
    slug: 'curacao',
    slug_locale_id: 'curacao',
    denonym_slug: 'curacao',
    denonym_slug_locale_id: 'curacao'
  },
  {
    id: 58,
    name: 'Cyprus',
    name_locale_id: 'Siprus',
    dial_code: '357',
    iso2: 'CY',
    iso3: 'CYP',
    denonym: 'Cyprus',
    denonym_locale_id: 'Siprus',
    slug: 'cyprus',
    slug_locale_id: 'siprus',
    denonym_slug: 'cyprus',
    denonym_slug_locale_id: 'siprus'
  },
  {
    id: 59,
    name: 'Czech Republic',
    name_locale_id: 'Republik Ceko',
    dial_code: '420',
    iso2: 'CZ',
    iso3: 'CZE',
    denonym: 'Czech Republic',
    denonym_locale_id: 'Republik Ceko',
    slug: 'czech-republic',
    slug_locale_id: 'republik-ceko',
    denonym_slug: 'czech-republic',
    denonym_slug_locale_id: 'republik-ceko'
  },
  {
    id: 63,
    name: 'Denmark',
    name_locale_id: 'Denmark',
    dial_code: '45',
    iso2: 'DK',
    iso3: 'DNK',
    denonym: 'Denmark',
    denonym_locale_id: 'Denmark',
    slug: 'denmark',
    slug_locale_id: 'denmark',
    denonym_slug: 'denmark',
    denonym_slug_locale_id: 'denmark'
  },
  {
    id: 64,
    name: 'Djibouti',
    name_locale_id: 'Djibouti',
    dial_code: '253',
    iso2: 'DJ',
    iso3: 'DJI',
    denonym: 'Djibouti',
    denonym_locale_id: 'Djibouti',
    slug: 'djibouti',
    slug_locale_id: 'djibouti',
    denonym_slug: 'djibouti',
    denonym_slug_locale_id: 'djibouti'
  },
  {
    id: 65,
    name: 'Dominica',
    name_locale_id: 'Dominika',
    dial_code: '1-767',
    iso2: 'DM',
    iso3: 'DMA',
    denonym: 'Dominica',
    denonym_locale_id: 'Dominika',
    slug: 'dominica',
    slug_locale_id: 'dominika',
    denonym_slug: 'dominica',
    denonym_slug_locale_id: 'dominika'
  },
  {
    id: 246,
    name: 'Dominican Republic',
    name_locale_id: 'Republik Dominika',
    dial_code: '1-809',
    iso2: 'DO',
    iso3: 'DOM',
    denonym: 'Dominican Republic',
    denonym_locale_id: 'Republik Dominika',
    slug: 'dominican-republic',
    slug_locale_id: 'republik-dominika',
    denonym_slug: 'dominican-republic',
    denonym_slug_locale_id: 'republik-dominika'
  },
  {
    id: 218,
    name: 'East Timor (Timor-Leste)',
    name_locale_id: 'Timor Timur (Timor-Leste)',
    dial_code: '670',
    iso2: 'TL',
    iso3: 'TLS',
    denonym: 'East Timor (Timor-Leste)',
    denonym_locale_id: 'Timor Timur (Timor-Leste)',
    slug: 'east-timor-timor-leste',
    slug_locale_id: 'timor-timur-timor-leste',
    denonym_slug: 'east-timor-timor-leste',
    denonym_slug_locale_id: 'timor-timur-timor-leste'
  },
  {
    id: 66,
    name: 'Ecuador',
    name_locale_id: 'Ekuador',
    dial_code: '593',
    iso2: 'EC',
    iso3: 'ECU',
    denonym: 'Ecuador',
    denonym_locale_id: 'Ekuador',
    slug: 'ecuador',
    slug_locale_id: 'ekuador',
    denonym_slug: 'ecuador',
    denonym_slug_locale_id: 'ekuador'
  },
  {
    id: 67,
    name: 'Egypt',
    name_locale_id: 'Mesir',
    dial_code: '20',
    iso2: 'EG',
    iso3: 'EGY',
    denonym: 'Egypt',
    denonym_locale_id: 'Mesir',
    slug: 'egypt',
    slug_locale_id: 'mesir',
    denonym_slug: 'egypt',
    denonym_slug_locale_id: 'mesir'
  },
  {
    id: 68,
    name: 'El Salvador',
    name_locale_id: 'El Salvador',
    dial_code: '503',
    iso2: 'SV',
    iso3: 'SLV',
    denonym: 'El Salvador',
    denonym_locale_id: 'El Salvador',
    slug: 'el-salvador',
    slug_locale_id: 'el-salvador',
    denonym_slug: 'el-salvador',
    denonym_slug_locale_id: 'el-salvador'
  },
  {
    id: 69,
    name: 'Equatorial Guinea',
    name_locale_id: 'Guinea Khatulistiwa',
    dial_code: '240',
    iso2: 'GQ',
    iso3: 'GNQ',
    denonym: 'Equatorial Guinea',
    denonym_locale_id: 'Guinea Khatulistiwa',
    slug: 'equatorial-guinea',
    slug_locale_id: 'guinea-khatulistiwa',
    denonym_slug: 'equatorial-guinea',
    denonym_slug_locale_id: 'guinea-khatulistiwa'
  },
  {
    id: 70,
    name: 'Eritrea',
    name_locale_id: 'Eritrea',
    dial_code: '291',
    iso2: 'ER',
    iso3: 'ERI',
    denonym: 'Eritrea',
    denonym_locale_id: 'Eritrea',
    slug: 'eritrea',
    slug_locale_id: 'eritrea',
    denonym_slug: 'eritrea',
    denonym_slug_locale_id: 'eritrea'
  },
  {
    id: 71,
    name: 'Estonia',
    name_locale_id: 'Estonia',
    dial_code: '372',
    iso2: 'EE',
    iso3: 'EST',
    denonym: 'Estonia',
    denonym_locale_id: 'Estonia',
    slug: 'estonia',
    slug_locale_id: 'estonia',
    denonym_slug: 'estonia',
    denonym_slug_locale_id: 'estonia'
  },
  {
    id: 72,
    name: 'Eswatini',
    name_locale_id: 'Eswatini',
    dial_code: '268',
    iso2: 'SZ',
    iso3: 'SWZ',
    denonym: 'Eswatini',
    denonym_locale_id: 'Eswatini',
    slug: 'eswatini',
    slug_locale_id: 'eswatini',
    denonym_slug: 'eswatini',
    denonym_slug_locale_id: 'eswatini'
  },
  {
    id: 73,
    name: 'Ethiopia',
    name_locale_id: 'Ethiopia',
    dial_code: '251',
    iso2: 'ET',
    iso3: 'ETH',
    denonym: 'Ethiopia',
    denonym_locale_id: 'Ethiopia',
    slug: 'ethiopia',
    slug_locale_id: 'ethiopia',
    denonym_slug: 'ethiopia',
    denonym_slug_locale_id: 'ethiopia'
  },
  {
    id: 74,
    name: 'Falkland Islands (Malvinas)',
    name_locale_id: 'Kepulauan Falkland (Malvinas)',
    dial_code: '500',
    iso2: 'FK',
    iso3: 'FLK',
    denonym: 'Falkland Islands (Malvinas)',
    denonym_locale_id: 'Kepulauan Falkland (Malvinas)',
    slug: 'falkland-islands-malvinas',
    slug_locale_id: 'kepulauan-falkland-malvinas',
    denonym_slug: 'falkland-islands-malvinas',
    denonym_slug_locale_id: 'kepulauan-falkland-malvinas'
  },
  {
    id: 75,
    name: 'Faroe Islands',
    name_locale_id: 'Kepulauan Faroe',
    dial_code: '298',
    iso2: 'FO',
    iso3: 'FRO',
    denonym: 'Faroe Islands',
    denonym_locale_id: 'Kepulauan Faroe',
    slug: 'faroe-islands',
    slug_locale_id: 'kepulauan-faroe',
    denonym_slug: 'faroe-islands',
    denonym_slug_locale_id: 'kepulauan-faroe'
  },
  {
    id: 76,
    name: 'Fiji',
    name_locale_id: 'Fiji',
    dial_code: '679',
    iso2: 'FJ',
    iso3: 'FJI',
    denonym: 'Fiji',
    denonym_locale_id: 'Fiji',
    slug: 'fiji',
    slug_locale_id: 'fiji',
    denonym_slug: 'fiji',
    denonym_slug_locale_id: 'fiji'
  },
  {
    id: 77,
    name: 'Finland',
    name_locale_id: 'Finlandia',
    dial_code: '358',
    iso2: 'FI',
    iso3: 'FIN',
    denonym: 'Finland',
    denonym_locale_id: 'Finlandia',
    slug: 'finland',
    slug_locale_id: 'finlandia',
    denonym_slug: 'finland',
    denonym_slug_locale_id: 'finlandia'
  },
  {
    id: 78,
    name: 'France',
    name_locale_id: 'Prancis',
    dial_code: '33',
    iso2: 'FR',
    iso3: 'FRA',
    denonym: 'France',
    denonym_locale_id: 'Prancis',
    slug: 'france',
    slug_locale_id: 'prancis',
    denonym_slug: 'france',
    denonym_slug_locale_id: 'prancis'
  },
  {
    id: 79,
    name: 'French Guiana',
    name_locale_id: 'Guyana Prancis',
    dial_code: '594',
    iso2: 'GF',
    iso3: 'GUF',
    denonym: 'French Guiana',
    denonym_locale_id: 'Guyana Prancis',
    slug: 'frech-guiana',
    slug_locale_id: 'guyana-prancis',
    denonym_slug: 'frech-guiana',
    denonym_slug_locale_id: 'guyana-prancis'
  },
  {
    id: 80,
    name: 'French Polynesia',
    name_locale_id: 'Polinesia Prancis',
    dial_code: '689',
    iso2: 'PF',
    iso3: 'PYF',
    denonym: 'French Polynesia',
    denonym_locale_id: 'Polinesia Prancis',
    slug: 'french-polynesia',
    slug_locale_id: 'polinesia-prancis',
    denonym_slug: 'french-polynesia',
    denonym_slug_locale_id: 'polinesia-prancis'
  },
  {
    id: 81,
    name: 'French Southern Territories',
    name_locale_id: 'Wilayah Selatan Prancis',
    dial_code: '262',
    iso2: 'TF',
    iso3: 'ATF',
    denonym: 'French Southern Territories',
    denonym_locale_id: 'Wilayah Selatan Prancis',
    slug: 'french-southern-territories',
    slug_locale_id: 'wilayah-selatan-prancis',
    denonym_slug: 'french-southern-territories',
    denonym_slug_locale_id: 'wilayah-selatan-prancis'
  },
  {
    id: 82,
    name: 'Gabon',
    name_locale_id: 'Gabon',
    dial_code: '241',
    iso2: 'GA',
    iso3: 'GAB',
    denonym: 'Gabon',
    denonym_locale_id: 'Gabon',
    slug: 'gabon',
    slug_locale_id: 'gabon',
    denonym_slug: 'gabon',
    denonym_slug_locale_id: 'gabon'
  },
  {
    id: 84,
    name: 'Georgia',
    name_locale_id: 'Georgia',
    dial_code: '995',
    iso2: 'GE',
    iso3: 'GEO',
    denonym: 'Georgia',
    denonym_locale_id: 'Georgia',
    slug: 'georgia',
    slug_locale_id: 'georgia',
    denonym_slug: 'georgia',
    denonym_slug_locale_id: 'georgia'
  },
  {
    id: 85,
    name: 'Germany',
    name_locale_id: 'Jerman',
    dial_code: '49',
    iso2: 'DE',
    iso3: 'DEU',
    denonym: 'Germany',
    denonym_locale_id: 'Jerman',
    slug: 'germany',
    slug_locale_id: 'jerman',
    denonym_slug: 'germany',
    denonym_slug_locale_id: 'jerman'
  },
  {
    id: 86,
    name: 'Ghana',
    name_locale_id: 'Ghana',
    dial_code: '233',
    iso2: 'GH',
    iso3: 'GHA',
    denonym: 'Ghana',
    denonym_locale_id: 'Ghana',
    slug: 'ghana',
    slug_locale_id: 'ghana',
    denonym_slug: 'ghana',
    denonym_slug_locale_id: 'ghana'
  },
  {
    id: 87,
    name: 'Gibraltar',
    name_locale_id: 'Gibraltar',
    dial_code: '350',
    iso2: 'GI',
    iso3: 'GIB',
    denonym: 'Gibraltar',
    denonym_locale_id: 'Gibraltar',
    slug: 'gibraltar',
    slug_locale_id: 'gibraltar',
    denonym_slug: 'gibraltar',
    denonym_slug_locale_id: 'gibraltar'
  },
  {
    id: 88,
    name: 'Greece',
    name_locale_id: 'Yunani',
    dial_code: '30',
    iso2: 'GR',
    iso3: 'GRC',
    denonym: 'Greece',
    denonym_locale_id: 'Yunani',
    slug: 'greece',
    slug_locale_id: 'yunani',
    denonym_slug: 'greece',
    denonym_slug_locale_id: 'yunani'
  },
  {
    id: 89,
    name: 'Greenland',
    name_locale_id: 'Greenland',
    dial_code: '299',
    iso2: 'GL',
    iso3: 'GRL',
    denonym: 'Greenland',
    denonym_locale_id: 'Greenland',
    slug: 'greenland',
    slug_locale_id: 'greenland',
    denonym_slug: 'greenland',
    denonym_slug_locale_id: 'greenland'
  },
  {
    id: 90,
    name: 'Grenada',
    name_locale_id: 'Grenada',
    dial_code: '1-473',
    iso2: 'GD',
    iso3: 'GRD',
    denonym: 'Grenada',
    denonym_locale_id: 'Grenada',
    slug: 'grenada',
    slug_locale_id: 'grenada',
    denonym_slug: 'grenada',
    denonym_slug_locale_id: 'grenada'
  },
  {
    id: 91,
    name: 'Guadeloupe',
    name_locale_id: 'Guadeloupe',
    dial_code: '590',
    iso2: 'GP',
    iso3: 'GLP',
    denonym: 'Guadeloupe',
    denonym_locale_id: 'Guadeloupe',
    slug: 'guadeloupe',
    slug_locale_id: 'guadeloupe',
    denonym_slug: 'guadeloupe',
    denonym_slug_locale_id: 'guadeloupe'
  },
  {
    id: 92,
    name: 'Guam',
    name_locale_id: 'Guam',
    dial_code: '1-671',
    iso2: 'GU',
    iso3: 'GUM',
    denonym: 'Guam',
    denonym_locale_id: 'Guam',
    slug: 'guam',
    slug_locale_id: 'guam',
    denonym_slug: 'guam',
    denonym_slug_locale_id: 'guam'
  },
  {
    id: 93,
    name: 'Guatemala',
    name_locale_id: 'Guatemala',
    dial_code: '502',
    iso2: 'GT',
    iso3: 'GTM',
    denonym: 'Guatemala',
    denonym_locale_id: 'Guatemala',
    slug: 'guatemala',
    slug_locale_id: 'guatemala',
    denonym_slug: 'guatemala',
    denonym_slug_locale_id: 'guatemala'
  },
  {
    id: 94,
    name: 'Guernsey',
    name_locale_id: 'Guernsey',
    dial_code: '44',
    iso2: 'GG',
    iso3: 'GGY',
    denonym: 'Guernsey',
    denonym_locale_id: 'Guernsey',
    slug: 'guernsey',
    slug_locale_id: 'guernsey',
    denonym_slug: 'guernsey',
    denonym_slug_locale_id: 'guernsey'
  },
  {
    id: 95,
    name: 'Guinea',
    name_locale_id: 'Guinea',
    dial_code: '224',
    iso2: 'GN',
    iso3: 'GIN',
    denonym: 'Guinea',
    denonym_locale_id: 'Guinea',
    slug: 'guinea',
    slug_locale_id: 'guinea',
    denonym_slug: 'guinea',
    denonym_slug_locale_id: 'guinea'
  },
  {
    id: 96,
    name: 'Guinea-Bissau',
    name_locale_id: 'Guinea-Bissau',
    dial_code: '245',
    iso2: 'GW',
    iso3: 'GNB',
    denonym: 'Guinea-Bissau',
    denonym_locale_id: 'Guinea-Bissau',
    slug: 'guinea-bissau',
    slug_locale_id: 'guinea-bissau',
    denonym_slug: 'guinea-bissau',
    denonym_slug_locale_id: 'guinea-bissau'
  },
  {
    id: 97,
    name: 'Guyana',
    name_locale_id: 'Guyana',
    dial_code: '592',
    iso2: 'GY',
    iso3: 'GUY',
    denonym: 'Guyana',
    denonym_locale_id: 'Guyana',
    slug: 'guyana',
    slug_locale_id: 'guyana',
    denonym_slug: 'guyana',
    denonym_slug_locale_id: 'guyana'
  },
  {
    id: 98,
    name: 'Haiti',
    name_locale_id: 'Haiti',
    dial_code: '509',
    iso2: 'HT',
    iso3: 'HTI',
    denonym: 'Haiti',
    denonym_locale_id: 'Haiti',
    slug: 'haiti',
    slug_locale_id: 'haiti',
    denonym_slug: 'haiti',
    denonym_slug_locale_id: 'haiti'
  },
  {
    id: 99,
    name: 'Heard Island and McDonald Islands',
    name_locale_id: 'Pulau Heard dan Kepulauan McDonald',
    dial_code: '672',
    iso2: 'HM',
    iso3: 'HMD',
    denonym: 'Heard Island and McDonald Islands',
    denonym_locale_id: 'Pulau Heard dan Kepulauan McDonald',
    slug: 'heard-island-and-mcdonald-islands',
    slug_locale_id: 'pulau-heard-dan-kepulauan-mcdonald',
    denonym_slug: 'heard-island-and-mcdonald-islands',
    denonym_slug_locale_id: 'pulau-heard-dan-kepulauan-mcdonald'
  },
  {
    id: 101,
    name: 'Honduras',
    name_locale_id: 'Honduras',
    dial_code: '504',
    iso2: 'HN',
    iso3: 'HND',
    denonym: 'Honduras',
    denonym_locale_id: 'Honduras',
    slug: 'honduras',
    slug_locale_id: 'honduras',
    denonym_slug: 'honduras',
    denonym_slug_locale_id: 'honduras'
  },
  {
    id: 46,
    name: 'Hongkong',
    name_locale_id: 'Hong Kong',
    dial_code: '852',
    iso2: 'HK',
    iso3: 'HKG',
    denonym: 'Hongkong',
    denonym_locale_id: 'Hong Kong',
    slug: 'hongkong',
    slug_locale_id: 'hongkong',
    denonym_slug: 'hongkong',
    denonym_slug_locale_id: 'hongkong'
  },
  {
    id: 102,
    name: 'Hungary',
    name_locale_id: 'Hongaria',
    dial_code: '36',
    iso2: 'HU',
    iso3: 'HUN',
    denonym: 'Hungary',
    denonym_locale_id: 'Hongaria',
    slug: 'hungary',
    slug_locale_id: 'hungaria',
    denonym_slug: 'hungary',
    denonym_slug_locale_id: 'hungaria'
  },
  {
    id: 103,
    name: 'Iceland',
    name_locale_id: 'Islandia',
    dial_code: '354',
    iso2: 'IS',
    iso3: 'ISL',
    denonym: 'Iceland',
    denonym_locale_id: 'Islandia',
    slug: 'iceland',
    slug_locale_id: 'islandia',
    denonym_slug: 'iceland',
    denonym_slug_locale_id: 'islandia'
  },
  {
    id: 104,
    name: 'India',
    name_locale_id: 'India',
    dial_code: '91',
    iso2: 'IN',
    iso3: 'IND',
    denonym: 'India',
    denonym_locale_id: 'India',
    slug: 'india',
    slug_locale_id: 'india',
    denonym_slug: 'india',
    denonym_slug_locale_id: 'india'
  },
  {
    id: 105,
    name: 'Indonesia',
    name_locale_id: 'Indonesia',
    dial_code: '62',
    iso2: 'ID',
    iso3: 'IDN',
    denonym: 'Indonesia',
    denonym_locale_id: 'Indonesia',
    slug: 'indonesia',
    slug_locale_id: 'indonesia',
    denonym_slug: 'indonesia',
    denonym_slug_locale_id: 'indonesia'
  },
  {
    id: 106,
    name: 'Iran',
    name_locale_id: 'Iran',
    dial_code: '98',
    iso2: 'IR',
    iso3: 'IRN',
    denonym: 'Iran',
    denonym_locale_id: 'Iran',
    slug: 'iran',
    slug_locale_id: 'iran',
    denonym_slug: 'iran',
    denonym_slug_locale_id: 'iran'
  },
  {
    id: 107,
    name: 'Iraq',
    name_locale_id: 'Irak',
    dial_code: '964',
    iso2: 'IQ',
    iso3: 'IRQ',
    denonym: 'Iraq',
    denonym_locale_id: 'Irak',
    slug: 'irag',
    slug_locale_id: 'irak',
    denonym_slug: 'irag',
    denonym_slug_locale_id: 'irak'
  },
  {
    id: 108,
    name: 'Ireland',
    name_locale_id: 'Irlandia',
    dial_code: '353',
    iso2: 'IE',
    iso3: 'IRL',
    denonym: 'Ireland',
    denonym_locale_id: 'Irlandia',
    slug: 'ireland',
    slug_locale_id: 'irlandia',
    denonym_slug: 'ireland',
    denonym_slug_locale_id: 'irlandia'
  },
  {
    id: 109,
    name: 'Isle of Man',
    name_locale_id: 'Pulau Man',
    dial_code: '44',
    iso2: 'IM',
    iso3: 'IMN',
    denonym: 'Isle of Man',
    denonym_locale_id: 'Pulau Man',
    slug: 'isle-of-man',
    slug_locale_id: 'pulau-man',
    denonym_slug: 'isle-of-man',
    denonym_slug_locale_id: 'pulau-man'
  },
  {
    id: 111,
    name: 'Italy',
    name_locale_id: 'Italia',
    dial_code: '39',
    iso2: 'IT',
    iso3: 'ITA',
    denonym: 'Italy',
    denonym_locale_id: 'Italia',
    slug: 'italy',
    slug_locale_id: 'italia',
    denonym_slug: 'italy',
    denonym_slug_locale_id: 'italia'
  },
  {
    id: 112,
    name: 'Jamaica',
    name_locale_id: 'Jamaika',
    dial_code: '1-876',
    iso2: 'JM',
    iso3: 'JAM',
    denonym: 'Jamaica',
    denonym_locale_id: 'Jamaika',
    slug: 'jamaica',
    slug_locale_id: 'jamaika',
    denonym_slug: 'jamaica',
    denonym_slug_locale_id: 'jamaika'
  },
  {
    id: 113,
    name: 'Japan',
    name_locale_id: 'Jepang',
    dial_code: '81',
    iso2: 'JP',
    iso3: 'JPN',
    denonym: 'Japan',
    denonym_locale_id: 'Jepang',
    slug: 'japan',
    slug_locale_id: 'jepang',
    denonym_slug: 'japan',
    denonym_slug_locale_id: 'jepang'
  },
  {
    id: 114,
    name: 'Jersey',
    name_locale_id: 'Jersey',
    dial_code: '44',
    iso2: 'JE',
    iso3: 'JEY',
    denonym: 'Jersey',
    denonym_locale_id: 'Jersey',
    slug: 'jersey',
    slug_locale_id: 'jersey',
    denonym_slug: 'jersey',
    denonym_slug_locale_id: 'jersey'
  },
  {
    id: 115,
    name: 'Jordan',
    name_locale_id: 'Yordania',
    dial_code: '962',
    iso2: 'JO',
    iso3: 'JOR',
    denonym: 'Jordan',
    denonym_locale_id: 'Yordania',
    slug: 'jordan',
    slug_locale_id: 'yordania',
    denonym_slug: 'jordan',
    denonym_slug_locale_id: 'yordania'
  },
  {
    id: 116,
    name: 'Kazakhstan',
    name_locale_id: 'Kazakhstan',
    dial_code: '7',
    iso2: 'KZ',
    iso3: 'KAZ',
    denonym: 'Kazakhstan',
    denonym_locale_id: 'Kazakhstan',
    slug: 'kazakhstan',
    slug_locale_id: 'kazakhstan',
    denonym_slug: 'kazakhstan',
    denonym_slug_locale_id: 'kazakhstan'
  },
  {
    id: 117,
    name: 'Kenya',
    name_locale_id: 'Kenya',
    dial_code: '254',
    iso2: 'KE',
    iso3: 'KEN',
    denonym: 'Kenya',
    denonym_locale_id: 'Kenya',
    slug: 'kenya',
    slug_locale_id: 'kenya',
    denonym_slug: 'kenya',
    denonym_slug_locale_id: 'kenya'
  },
  {
    id: 118,
    name: 'Kiribati',
    name_locale_id: 'Kiribati',
    dial_code: '686',
    iso2: 'KI',
    iso3: 'KIR',
    denonym: 'Kiribati',
    denonym_locale_id: 'Kiribati',
    slug: 'kiribati',
    slug_locale_id: 'kiribati',
    denonym_slug: 'kiribati',
    denonym_slug_locale_id: 'kiribati'
  },
  {
    id: 61,
    name: 'Korea, North',
    name_locale_id: 'Korea Utara',
    dial_code: '850',
    iso2: 'KP',
    iso3: 'PRK',
    denonym: 'Korea, North',
    denonym_locale_id: 'Korea Utara',
    slug: 'north-korea',
    slug_locale_id: 'korea-utara',
    denonym_slug: 'north-korea',
    denonym_slug_locale_id: 'korea-utara'
  },
  {
    id: 176,
    name: 'Korea, South',
    name_locale_id: 'Korea Selatan',
    dial_code: '82',
    iso2: 'KR',
    iso3: 'KOR',
    denonym: 'Korea, South',
    denonym_locale_id: 'Korea Selatan',
    slug: 'south-korea',
    slug_locale_id: 'korea-selatan',
    denonym_slug: 'south-korea',
    denonym_slug_locale_id: 'korea-selatan'
  },
  {
    id: 250,
    name: 'Kosovo',
    name_locale_id: 'Kosovo',
    dial_code: '383',
    iso2: 'XK',
    iso3: 'XKX',
    denonym: 'Kosovo',
    denonym_locale_id: 'Kosovo',
    slug: 'kosovo',
    slug_locale_id: 'kosovo',
    denonym_slug: 'kosovo',
    denonym_slug_locale_id: 'kosovo'
  },
  {
    id: 119,
    name: 'Kuwait',
    name_locale_id: 'Kuwait',
    dial_code: '965',
    iso2: 'KW',
    iso3: 'KWT',
    denonym: 'Kuwait',
    denonym_locale_id: 'Kuwait',
    slug: 'kuwait',
    slug_locale_id: 'kuwait',
    denonym_slug: 'kuwait',
    denonym_slug_locale_id: 'kuwait'
  },
  {
    id: 120,
    name: 'Kyrgyzstan',
    name_locale_id: 'Kirgistan',
    dial_code: '996',
    iso2: 'KG',
    iso3: 'KGZ',
    denonym: 'Kyrgyzstan',
    denonym_locale_id: 'Kirgistan',
    slug: 'kyrgyzstan',
    slug_locale_id: 'kirgistan',
    denonym_slug: 'kyrgyzstan',
    denonym_slug_locale_id: 'kirgistan'
  },
  {
    id: 121,
    name: 'Laos',
    name_locale_id: 'Laos',
    dial_code: '856',
    iso2: 'LA',
    iso3: 'LAO',
    denonym: 'Laos',
    denonym_locale_id: 'Laos',
    slug: 'laos',
    slug_locale_id: 'laos',
    denonym_slug: 'laos',
    denonym_slug_locale_id: 'laos'
  },
  {
    id: 122,
    name: 'Latvia',
    name_locale_id: 'Latvia',
    dial_code: '371',
    iso2: 'LV',
    iso3: 'LVA',
    denonym: 'Latvia',
    denonym_locale_id: 'Latvia',
    slug: 'latvia',
    slug_locale_id: 'latvia',
    denonym_slug: 'latvia',
    denonym_slug_locale_id: 'latvia'
  },
  {
    id: 123,
    name: 'Lebanon',
    name_locale_id: 'Lebanon',
    dial_code: '961',
    iso2: 'LB',
    iso3: 'LBN',
    denonym: 'Lebanon',
    denonym_locale_id: 'Lebanon',
    slug: 'lebanon',
    slug_locale_id: 'lebanon',
    denonym_slug: 'lebanon',
    denonym_slug_locale_id: 'lebanon'
  },
  {
    id: 124,
    name: 'Lesotho',
    name_locale_id: 'Lesotho',
    dial_code: '266',
    iso2: 'LS',
    iso3: 'LSO',
    denonym: 'Lesotho',
    denonym_locale_id: 'Lesotho',
    slug: 'lesotho',
    slug_locale_id: 'lesotho',
    denonym_slug: 'lesotho',
    denonym_slug_locale_id: 'lesotho'
  },
  {
    id: 125,
    name: 'Liberia',
    name_locale_id: 'Liberia',
    dial_code: '231',
    iso2: 'LR',
    iso3: 'LBR',
    denonym: 'Liberia',
    denonym_locale_id: 'Liberia',
    slug: 'liberia',
    slug_locale_id: 'liberia',
    denonym_slug: 'liberia',
    denonym_slug_locale_id: 'liberia'
  },
  {
    id: 126,
    name: 'Libya',
    name_locale_id: 'Libya',
    dial_code: '218',
    iso2: 'LY',
    iso3: 'LBY',
    denonym: 'Libya',
    denonym_locale_id: 'Libya',
    slug: 'libya',
    slug_locale_id: 'libya',
    denonym_slug: 'libya',
    denonym_slug_locale_id: 'libya'
  },
  {
    id: 127,
    name: 'Liechtenstein',
    name_locale_id: 'Liechtenstein',
    dial_code: '423',
    iso2: 'LI',
    iso3: 'LIE',
    denonym: 'Liechtenstein',
    denonym_locale_id: 'Liechtenstein',
    slug: 'liechtenstein',
    slug_locale_id: 'liechtenstein',
    denonym_slug: 'liechtenstein',
    denonym_slug_locale_id: 'liechtenstein'
  },
  {
    id: 128,
    name: 'Lithuania',
    name_locale_id: 'Lituania',
    dial_code: '370',
    iso2: 'LT',
    iso3: 'LTU',
    denonym: 'Lithuania',
    denonym_locale_id: 'Lituania',
    slug: 'lithuania',
    slug_locale_id: 'lituania',
    denonym_slug: 'lithuania',
    denonym_slug_locale_id: 'lituania'
  },
  {
    id: 129,
    name: 'Luxembourg',
    name_locale_id: 'Luksemburg',
    dial_code: '352',
    iso2: 'LU',
    iso3: 'LUX',
    denonym: 'Luxembourg',
    denonym_locale_id: 'Luksemburg',
    slug: 'luxembourg',
    slug_locale_id: 'luksemburg',
    denonym_slug: 'luxembourg',
    denonym_slug_locale_id: 'luksemburg'
  },
  {
    id: 47,
    name: 'Macau',
    name_locale_id: 'Makau',
    dial_code: '853',
    iso2: 'MO',
    iso3: 'MAC',
    denonym: 'Macau',
    denonym_locale_id: 'Makau',
    slug: 'macau',
    slug_locale_id: 'makau',
    denonym_slug: 'macau',
    denonym_slug_locale_id: 'makau'
  },
  {
    id: 130,
    name: 'Madagascar',
    name_locale_id: 'Madagaskar',
    dial_code: '261',
    iso2: 'MG',
    iso3: 'MDG',
    denonym: 'Madagascar',
    denonym_locale_id: 'Madagaskar',
    slug: 'madagascar',
    slug_locale_id: 'madagaskar',
    denonym_slug: 'madagascar',
    denonym_slug_locale_id: 'madagaskar'
  },
  {
    id: 131,
    name: 'Malawi',
    name_locale_id: 'Malawi',
    dial_code: '265',
    iso2: 'MW',
    iso3: 'MWI',
    denonym: 'Malawi',
    denonym_locale_id: 'Malawi',
    slug: 'malawi',
    slug_locale_id: 'malawi',
    denonym_slug: 'malawi',
    denonym_slug_locale_id: 'malawi'
  },
  {
    id: 132,
    name: 'Malaysia',
    name_locale_id: 'Malaysia',
    dial_code: '60',
    iso2: 'MY',
    iso3: 'MYS',
    denonym: 'Malaysia',
    denonym_locale_id: 'Malaysia',
    slug: 'malaysia',
    slug_locale_id: 'malaysia',
    denonym_slug: 'malaysia',
    denonym_slug_locale_id: 'malaysia'
  },
  {
    id: 133,
    name: 'Maldives',
    name_locale_id: 'Maladewa',
    dial_code: '960',
    iso2: 'MV',
    iso3: 'MDV',
    denonym: 'Maldives',
    denonym_locale_id: 'Maladewa',
    slug: 'maldives',
    slug_locale_id: 'maladewa',
    denonym_slug: 'maldives',
    denonym_slug_locale_id: 'maladewa'
  },
  {
    id: 134,
    name: 'Mali',
    name_locale_id: 'Mali',
    dial_code: '223',
    iso2: 'ML',
    iso3: 'MLI',
    denonym: 'Mali',
    denonym_locale_id: 'Mali',
    slug: 'mali',
    slug_locale_id: 'mali',
    denonym_slug: 'mali',
    denonym_slug_locale_id: 'mali'
  },
  {
    id: 135,
    name: 'Malta',
    name_locale_id: 'Malta',
    dial_code: '356',
    iso2: 'MT',
    iso3: 'MLT',
    denonym: 'Malta',
    denonym_locale_id: 'Malta',
    slug: 'malta',
    slug_locale_id: 'malta',
    denonym_slug: 'malta',
    denonym_slug_locale_id: 'malta'
  },
  {
    id: 136,
    name: 'Marshall Islands',
    name_locale_id: 'Kepulauan Marshall',
    dial_code: '692',
    iso2: 'MH',
    iso3: 'MHL',
    denonym: 'Marshall Islands',
    denonym_locale_id: 'Kepulauan Marshall',
    slug: 'marshall-islands',
    slug_locale_id: 'kepulauan-marshall',
    denonym_slug: 'marshall-islands',
    denonym_slug_locale_id: 'kepulauan-marshall'
  },
  {
    id: 137,
    name: 'Martinique',
    name_locale_id: 'Martinique',
    dial_code: '596',
    iso2: 'MQ',
    iso3: 'MTQ',
    denonym: 'Martinique',
    denonym_locale_id: 'Martinique',
    slug: 'martinique',
    slug_locale_id: 'martinique',
    denonym_slug: 'martinique',
    denonym_slug_locale_id: 'martinique'
  },
  {
    id: 138,
    name: 'Mauritania',
    name_locale_id: 'Mauritania',
    dial_code: '222',
    iso2: 'MR',
    iso3: 'MRT',
    denonym: 'Mauritania',
    denonym_locale_id: 'Mauritania',
    slug: 'mauritania',
    slug_locale_id: 'mauritania',
    denonym_slug: 'mauritania',
    denonym_slug_locale_id: 'mauritania'
  },
  {
    id: 139,
    name: 'Mauritius',
    name_locale_id: 'Mauritius',
    dial_code: '230',
    iso2: 'MU',
    iso3: 'MUS',
    denonym: 'Mauritius',
    denonym_locale_id: 'Mauritius',
    slug: 'mauritius',
    slug_locale_id: 'mauritius',
    denonym_slug: 'mauritius',
    denonym_slug_locale_id: 'mauritius'
  },
  {
    id: 140,
    name: 'Mayotte',
    name_locale_id: 'Mayotte',
    dial_code: '262',
    iso2: 'YT',
    iso3: 'MYT',
    denonym: 'Mayotte',
    denonym_locale_id: 'Mayotte',
    slug: 'mayotte',
    slug_locale_id: 'mayotte',
    denonym_slug: 'mayotte',
    denonym_slug_locale_id: 'mayotte'
  },
  {
    id: 141,
    name: 'Mexico',
    name_locale_id: 'Meksiko',
    dial_code: '52',
    iso2: 'MX',
    iso3: 'MEX',
    denonym: 'Mexico',
    denonym_locale_id: 'Meksiko',
    slug: 'mexico',
    slug_locale_id: 'meksiko',
    denonym_slug: 'mexico',
    denonym_slug_locale_id: 'meksiko'
  },
  {
    id: 142,
    name: 'Micronesia, Federated States of',
    name_locale_id: 'Negara Federasi Mikronesia',
    dial_code: '691',
    iso2: 'FM',
    iso3: 'FSM',
    denonym: 'Micronesia, Federated States of',
    denonym_locale_id: 'Negara Federasi Mikronesia',
    slug: 'federated-states-of-micronesia',
    slug_locale_id: 'negara-federasi-mikronesia',
    denonym_slug: 'federated-states-of-micronesia',
    denonym_slug_locale_id: 'negara-federasi-mikronesia'
  },
  {
    id: 177,
    name: 'Moldova',
    name_locale_id: 'Moldova',
    dial_code: '373',
    iso2: 'MD',
    iso3: 'MDA',
    denonym: 'Moldova',
    denonym_locale_id: 'Moldova',
    slug: 'moldova',
    slug_locale_id: 'moldova',
    denonym_slug: 'moldova',
    denonym_slug_locale_id: 'moldova'
  },
  {
    id: 143,
    name: 'Monaco',
    name_locale_id: 'Monako',
    dial_code: '377',
    iso2: 'MC',
    iso3: 'MCO',
    denonym: 'Monaco',
    denonym_locale_id: 'Monako',
    slug: 'monaco',
    slug_locale_id: 'monako',
    denonym_slug: 'monaco',
    denonym_slug_locale_id: 'monako'
  },
  {
    id: 144,
    name: 'Mongolia',
    name_locale_id: 'Mongolia',
    dial_code: '976',
    iso2: 'MN',
    iso3: 'MNG',
    denonym: 'Mongolia',
    denonym_locale_id: 'Mongolia',
    slug: 'mongolia',
    slug_locale_id: 'mongolia',
    denonym_slug: 'mongolia',
    denonym_slug_locale_id: 'mongolia'
  },
  {
    id: 145,
    name: 'Montenegro',
    name_locale_id: 'Montenegro',
    dial_code: '382',
    iso2: 'ME',
    iso3: 'MNE',
    denonym: 'Montenegro',
    denonym_locale_id: 'Montenegro',
    slug: 'montenegro',
    slug_locale_id: 'montenegro',
    denonym_slug: 'montenegro',
    denonym_slug_locale_id: 'montenegro'
  },
  {
    id: 146,
    name: 'Montserrat',
    name_locale_id: 'Montserrat',
    dial_code: '1-664',
    iso2: 'MS',
    iso3: 'MSR',
    denonym: 'Montserrat',
    denonym_locale_id: 'Montserrat',
    slug: 'montserrat',
    slug_locale_id: 'montserrat',
    denonym_slug: 'montserrat',
    denonym_slug_locale_id: 'montserrat'
  },
  {
    id: 147,
    name: 'Morocco',
    name_locale_id: 'Maroko',
    dial_code: '212',
    iso2: 'MA',
    iso3: 'MAR',
    denonym: 'Morocco',
    denonym_locale_id: 'Maroko',
    slug: 'morocco',
    slug_locale_id: 'maroko',
    denonym_slug: 'morocco',
    denonym_slug_locale_id: 'maroko'
  },
  {
    id: 148,
    name: 'Mozambique',
    name_locale_id: 'Mozambik',
    dial_code: '258',
    iso2: 'MZ',
    iso3: 'MOZ',
    denonym: 'Mozambique',
    denonym_locale_id: 'Mozambik',
    slug: 'mozambique',
    slug_locale_id: 'mozambik',
    denonym_slug: 'mozambique',
    denonym_slug_locale_id: 'mozambik'
  },
  {
    id: 149,
    name: 'Myanmar (Burma)',
    name_locale_id: 'Myanmar (Burma)',
    dial_code: '95',
    iso2: 'MM',
    iso3: 'MMR',
    denonym: 'Myanmar (Burma)',
    denonym_locale_id: 'Myanmar (Burma)',
    slug: 'myanmar-burma',
    slug_locale_id: 'myanmar-burma',
    denonym_slug: 'myanmar-burma',
    denonym_slug_locale_id: 'myanmar-burma'
  },
  {
    id: 150,
    name: 'Namibia',
    name_locale_id: 'Namibia',
    dial_code: '264',
    iso2: 'NA',
    iso3: 'NAM',
    denonym: 'Namibia',
    denonym_locale_id: 'Namibia',
    slug: 'namibia',
    slug_locale_id: 'namibia',
    denonym_slug: 'namibia',
    denonym_slug_locale_id: 'namibia'
  },
  {
    id: 151,
    name: 'Nauru',
    name_locale_id: 'Nauru',
    dial_code: '674',
    iso2: 'NR',
    iso3: 'NRU',
    denonym: 'Nauru',
    denonym_locale_id: 'Nauru',
    slug: 'nauru',
    slug_locale_id: 'nauru',
    denonym_slug: 'nauru',
    denonym_slug_locale_id: 'nauru'
  },
  {
    id: 152,
    name: 'Nepal',
    name_locale_id: 'Nepal',
    dial_code: '977',
    iso2: 'NP',
    iso3: 'NPL',
    denonym: 'Nepal',
    denonym_locale_id: 'Nepal',
    slug: 'nepal',
    slug_locale_id: 'nepal',
    denonym_slug: 'nepal',
    denonym_slug_locale_id: 'nepal'
  },
  {
    id: 153,
    name: 'Netherlands',
    name_locale_id: 'Belanda',
    dial_code: '31',
    iso2: 'NL',
    iso3: 'NLD',
    denonym: 'Netherlands',
    denonym_locale_id: 'Belanda',
    slug: 'netherlands',
    slug_locale_id: 'belanda',
    denonym_slug: 'netherlands',
    denonym_slug_locale_id: 'belanda'
  },
  {
    id: 154,
    name: 'New Caledonia',
    name_locale_id: 'Kaledonia Baru',
    dial_code: '687',
    iso2: 'NC',
    iso3: 'NCL',
    denonym: 'New Caledonia',
    denonym_locale_id: 'Kaledonia Baru',
    slug: 'new-caledonia',
    slug_locale_id: 'kaledonia-baru',
    denonym_slug: 'new-caledonia',
    denonym_slug_locale_id: 'kaledonia-baru'
  },
  {
    id: 155,
    name: 'New Zealand',
    name_locale_id: 'Selandia Baru',
    dial_code: '64',
    iso2: 'NZ',
    iso3: 'NZL',
    denonym: 'New Zealand',
    denonym_locale_id: 'Selandia Baru',
    slug: 'new-zealand',
    slug_locale_id: 'selandia-baru',
    denonym_slug: 'new-zealand',
    denonym_slug_locale_id: 'selandia-baru'
  },
  {
    id: 156,
    name: 'Nicaragua',
    name_locale_id: 'Nikaragua',
    dial_code: '505',
    iso2: 'NI',
    iso3: 'NIC',
    denonym: 'Nicaragua',
    denonym_locale_id: 'Nikaragua',
    slug: 'nicaragua',
    slug_locale_id: 'nikaragua',
    denonym_slug: 'nicaragua',
    denonym_slug_locale_id: 'nikaragua'
  },
  {
    id: 157,
    name: 'Niger',
    name_locale_id: 'Niger',
    dial_code: '227',
    iso2: 'NE',
    iso3: 'NER',
    denonym: 'Niger',
    denonym_locale_id: 'Niger',
    slug: 'niger',
    slug_locale_id: 'niger',
    denonym_slug: 'niger',
    denonym_slug_locale_id: 'niger'
  },
  {
    id: 158,
    name: 'Nigeria',
    name_locale_id: 'Nigeria',
    dial_code: '234',
    iso2: 'NG',
    iso3: 'NGA',
    denonym: 'Nigeria',
    denonym_locale_id: 'Nigeria',
    slug: 'nigeria',
    slug_locale_id: 'nigeria',
    denonym_slug: 'nigeria',
    denonym_slug_locale_id: 'nigeria'
  },
  {
    id: 159,
    name: 'Niue',
    name_locale_id: 'Niue',
    dial_code: '683',
    iso2: 'NU',
    iso3: 'NIU',
    denonym: 'Niue',
    denonym_locale_id: 'Niue',
    slug: 'niue',
    slug_locale_id: 'niue',
    denonym_slug: 'niue',
    denonym_slug_locale_id: 'niue'
  },
  {
    id: 160,
    name: 'Norfolk Island',
    name_locale_id: 'Pulau Norfolk',
    dial_code: '672',
    iso2: 'NF',
    iso3: 'NFK',
    denonym: 'Norfolk Island',
    denonym_locale_id: 'Pulau Norfolk',
    slug: 'norfolk-island',
    slug_locale_id: 'pulau-norfolk',
    denonym_slug: 'norfolk-island',
    denonym_slug_locale_id: 'pulau-norfolk'
  },
  {
    id: 161,
    name: 'Northern Mariana Islands',
    name_locale_id: 'Kepulauan Mariana Utara',
    dial_code: '1-670',
    iso2: 'MP',
    iso3: 'MNP',
    denonym: 'Northern Mariana Islands',
    denonym_locale_id: 'Kepulauan Mariana Utara',
    slug: 'northern-mariana-islands',
    slug_locale_id: 'kepulauan-mariana-utara',
    denonym_slug: 'northern-mariana-islands',
    denonym_slug_locale_id: 'kepulauan-mariana-utara'
  },
  {
    id: 217,
    name: 'North Macedonia',
    name_locale_id: 'Makedonia Utara',
    dial_code: '389',
    iso2: 'MK',
    iso3: 'MKD',
    denonym: 'North Macedonia',
    denonym_locale_id: 'Makedonia Utara',
    slug: 'north-macedonia',
    slug_locale_id: 'makedonia-utara',
    denonym_slug: 'north-macedonia',
    denonym_slug_locale_id: 'makedonia-utara'
  },
  {
    id: 162,
    name: 'Norway',
    name_locale_id: 'Norwegia',
    dial_code: '47',
    iso2: 'NO',
    iso3: 'NOR',
    denonym: 'Norway',
    denonym_locale_id: 'Norwegia',
    slug: 'norway',
    slug_locale_id: 'norwegia',
    denonym_slug: 'norway',
    denonym_slug_locale_id: 'norwegia'
  },
  {
    id: 163,
    name: 'Oman',
    name_locale_id: 'Oman',
    dial_code: '968',
    iso2: 'OM',
    iso3: 'OMN',
    denonym: 'Oman',
    denonym_locale_id: 'Oman',
    slug: 'oman',
    slug_locale_id: 'oman',
    denonym_slug: 'oman',
    denonym_slug_locale_id: 'oman'
  },
  {
    id: 164,
    name: 'Pakistan',
    name_locale_id: 'Pakistan',
    dial_code: '92',
    iso2: 'PK',
    iso3: 'PAK',
    denonym: 'Pakistan',
    denonym_locale_id: 'Pakistan',
    slug: 'pakistan',
    slug_locale_id: 'pakistan',
    denonym_slug: 'pakistan',
    denonym_slug_locale_id: 'pakistan'
  },
  {
    id: 165,
    name: 'Palau',
    name_locale_id: 'Palau',
    dial_code: '680',
    iso2: 'PW',
    iso3: 'PLW',
    denonym: 'Palau',
    denonym_locale_id: 'Palau',
    slug: 'palau',
    slug_locale_id: 'palau',
    denonym_slug: 'palau',
    denonym_slug_locale_id: 'palau'
  },
  {
    id: 208,
    name: 'Palestine',
    name_locale_id: 'Palestina',
    dial_code: '970',
    iso2: 'PS',
    iso3: 'PSE',
    denonym: 'Palestine',
    denonym_locale_id: 'Palestina',
    slug: 'palestine',
    slug_locale_id: 'palestina',
    denonym_slug: 'palestine',
    denonym_slug_locale_id: 'palestina'
  },
  {
    id: 166,
    name: 'Panama',
    name_locale_id: 'Panama',
    dial_code: '507',
    iso2: 'PA',
    iso3: 'PAN',
    denonym: 'Panama',
    denonym_locale_id: 'Panama',
    slug: 'panama',
    slug_locale_id: 'panama',
    denonym_slug: 'panama',
    denonym_slug_locale_id: 'panama'
  },
  {
    id: 167,
    name: 'Papua New Guinea',
    name_locale_id: 'Papua Nugini',
    dial_code: '675',
    iso2: 'PG',
    iso3: 'PNG',
    denonym: 'Papua New Guinea',
    denonym_locale_id: 'Papua Nugini',
    slug: 'papua-new-guinea',
    slug_locale_id: 'papua-nugini',
    denonym_slug: 'papua-new-guinea',
    denonym_slug_locale_id: 'papua-nugini'
  },
  {
    id: 168,
    name: 'Paraguay',
    name_locale_id: 'Paraguay',
    dial_code: '595',
    iso2: 'PY',
    iso3: 'PRY',
    denonym: 'Paraguay',
    denonym_locale_id: 'Paraguay',
    slug: 'paraguay',
    slug_locale_id: 'paraguay',
    denonym_slug: 'paraguay',
    denonym_slug_locale_id: 'paraguay'
  },
  {
    id: 169,
    name: 'Peru',
    name_locale_id: 'Peru',
    dial_code: '51',
    iso2: 'PE',
    iso3: 'PER',
    denonym: 'Peru',
    denonym_locale_id: 'Peru',
    slug: 'peru',
    slug_locale_id: 'peru',
    denonym_slug: 'peru',
    denonym_slug_locale_id: 'peru'
  },
  {
    id: 170,
    name: 'Philippines',
    name_locale_id: 'Filipina',
    dial_code: '63',
    iso2: 'PH',
    iso3: 'PHL',
    denonym: 'Philippines',
    denonym_locale_id: 'Filipina',
    slug: 'philippines',
    slug_locale_id: 'filipina',
    denonym_slug: 'philippines',
    denonym_slug_locale_id: 'filipina'
  },
  {
    id: 171,
    name: 'Pitcairn',
    name_locale_id: 'Pitcairn',
    dial_code: '870',
    iso2: 'PN',
    iso3: 'PCN',
    denonym: 'Pitcairn',
    denonym_locale_id: 'Pitcairn',
    slug: 'pitcairn',
    slug_locale_id: 'pitcairn',
    denonym_slug: 'pitcairn',
    denonym_slug_locale_id: 'pitcairn'
  },
  {
    id: 172,
    name: 'Poland',
    name_locale_id: 'Polandia',
    dial_code: '48',
    iso2: 'PL',
    iso3: 'POL',
    denonym: 'Poland',
    denonym_locale_id: 'Polandia',
    slug: 'poland',
    slug_locale_id: 'polandia',
    denonym_slug: 'poland',
    denonym_slug_locale_id: 'polandia'
  },
  {
    id: 173,
    name: 'Portugal',
    name_locale_id: 'Portugal',
    dial_code: '351',
    iso2: 'PT',
    iso3: 'PRT',
    denonym: 'Portugal',
    denonym_locale_id: 'Portugal',
    slug: 'portugal',
    slug_locale_id: 'portugal',
    denonym_slug: 'portugal',
    denonym_slug_locale_id: 'portugal'
  },
  {
    id: 174,
    name: 'Puerto Rico',
    name_locale_id: 'Puerto Rico',
    dial_code: '1',
    iso2: 'PR',
    iso3: 'PRI',
    denonym: 'Puerto Rico',
    denonym_locale_id: 'Puerto Rico',
    slug: 'puerto-rico',
    slug_locale_id: 'puerto-rico',
    denonym_slug: 'puerto-rico',
    denonym_slug_locale_id: 'puerto-rico'
  },
  {
    id: 175,
    name: 'Qatar',
    name_locale_id: 'Qatar',
    dial_code: '974',
    iso2: 'QA',
    iso3: 'QAT',
    denonym: 'Qatar',
    denonym_locale_id: 'Qatar',
    slug: 'qatar',
    slug_locale_id: 'qatar',
    denonym_slug: 'qatar',
    denonym_slug_locale_id: 'qatar'
  },
  {
    id: 181,
    name: 'Réunion',
    name_locale_id: 'Reunion',
    dial_code: '262',
    iso2: 'RE',
    iso3: 'REU',
    denonym: 'Réunion',
    denonym_locale_id: 'Reunion',
    slug: 'reunion',
    slug_locale_id: 'reunion',
    denonym_slug: 'reunion',
    denonym_slug_locale_id: 'reunion'
  },
  {
    id: 178,
    name: 'Romania',
    name_locale_id: 'Rumania',
    dial_code: '40',
    iso2: 'RO',
    iso3: 'ROU',
    denonym: 'Romania',
    denonym_locale_id: 'Rumania',
    slug: 'romania',
    slug_locale_id: 'rumania',
    denonym_slug: 'romania',
    denonym_slug_locale_id: 'rumania'
  },
  {
    id: 179,
    name: 'Russia',
    name_locale_id: 'Rusia',
    dial_code: '7',
    iso2: 'RU',
    iso3: 'RUS',
    denonym: 'Russia',
    denonym_locale_id: 'Rusia',
    slug: 'russia',
    slug_locale_id: 'rusia',
    denonym_slug: 'russia',
    denonym_slug_locale_id: 'rusia'
  },
  {
    id: 180,
    name: 'Rwanda',
    name_locale_id: 'Rwanda',
    dial_code: '250',
    iso2: 'RW',
    iso3: 'RWA',
    denonym: 'Rwanda',
    denonym_locale_id: 'Rwanda',
    slug: 'rwanda',
    slug_locale_id: 'rwanda',
    denonym_slug: 'rwanda',
    denonym_slug_locale_id: 'rwanda'
  },
  {
    id: 182,
    name: 'Saint Barthélemy',
    name_locale_id: 'Saint Barthélemy',
    dial_code: '590',
    iso2: 'BL',
    iso3: 'BLM',
    denonym: 'Saint Barthélemy',
    denonym_locale_id: 'Saint Barthélemy',
    slug: 'saint-barthelemy',
    slug_locale_id: 'saint-barthelemy',
    denonym_slug: 'saint-barthelemy',
    denonym_slug_locale_id: 'saint-barthelemy'
  },
  {
    id: 183,
    name: 'Saint Helena',
    name_locale_id: 'Saint Helena',
    dial_code: '290',
    iso2: 'SH',
    iso3: 'SHN',
    denonym: 'Saint Helena',
    denonym_locale_id: 'Saint Helena',
    slug: 'saint-helena',
    slug_locale_id: 'saint-helena',
    denonym_slug: 'saint-helena',
    denonym_slug_locale_id: 'saint-helena'
  },
  {
    id: 184,
    name: 'Saint Kitts and Nevis',
    name_locale_id: 'Saint Kitts dan Nevis',
    dial_code: '1-869',
    iso2: 'KN',
    iso3: 'KNA',
    denonym: 'Saint Kitts and Nevis',
    denonym_locale_id: 'Saint Kitts dan Nevis',
    slug: 'saint-kitts-and-nevis',
    slug_locale_id: 'saint-kitts-dan-nevis',
    denonym_slug: 'saint-kitts-and-nevis',
    denonym_slug_locale_id: 'saint-kitts-dan-nevis'
  },
  {
    id: 185,
    name: 'Saint Lucia',
    name_locale_id: 'Saint Lucia',
    dial_code: '1-758',
    iso2: 'LC',
    iso3: 'LCA',
    denonym: 'Saint Lucia',
    denonym_locale_id: 'Saint Lucia',
    slug: 'saint-lucia',
    slug_locale_id: 'saint-lucia',
    denonym_slug: 'saint-lucia',
    denonym_slug_locale_id: 'saint-lucia'
  },
  {
    id: 186,
    name: 'Saint Martin (French Part)',
    name_locale_id: 'Saint Martin (Bagian Prancis)',
    dial_code: '590',
    iso2: 'MF',
    iso3: 'MAF',
    denonym: 'Saint Martin (French Part)',
    denonym_locale_id: 'Saint Martin (Bagian Prancis)',
    slug: 'saint-martin-frech-part',
    slug_locale_id: 'saint-martin-bagian-prancis',
    denonym_slug: 'saint-martin-frech-part',
    denonym_slug_locale_id: 'saint-martin-bagian-prancis'
  },
  {
    id: 187,
    name: 'Saint Pierre and Miquelon',
    name_locale_id: 'Saint Pierre dan Miquelon',
    dial_code: '508',
    iso2: 'PM',
    iso3: 'SPM',
    denonym: 'Saint Pierre and Miquelon',
    denonym_locale_id: 'Saint Pierre dan Miquelon',
    slug: 'saint-pierre-and-miquelon',
    slug_locale_id: 'saint-pierre-dan-miquelon',
    denonym_slug: 'saint-pierre-and-miquelon',
    denonym_slug_locale_id: 'saint-pierre-dan-miquelon'
  },
  {
    id: 188,
    name: 'Saint Vincent and the Grenadines',
    name_locale_id: 'Saint Vincent dan Grenadines',
    dial_code: '1-784',
    iso2: 'VC',
    iso3: 'VCT',
    denonym: 'Saint Vincent and the Grenadines',
    denonym_locale_id: 'Saint Vincent dan Grenadines',
    slug: 'saint-vincent-and-the-grenadines',
    slug_locale_id: 'saint-vincent-dan-grenadines',
    denonym_slug: 'saint-vincent-and-the-grenadines',
    denonym_slug_locale_id: 'saint-vincent-dan-grenadines'
  },
  {
    id: 189,
    name: 'Samoa',
    name_locale_id: 'Samoa',
    dial_code: '685',
    iso2: 'WS',
    iso3: 'WSM',
    denonym: 'Samoa',
    denonym_locale_id: 'Samoa',
    slug: 'samoa',
    slug_locale_id: 'samoa',
    denonym_slug: 'samoa',
    denonym_slug_locale_id: 'samoa'
  },
  {
    id: 190,
    name: 'San Marino',
    name_locale_id: 'San Marino',
    dial_code: '378',
    iso2: 'SM',
    iso3: 'SMR',
    denonym: 'San Marino',
    denonym_locale_id: 'San Marino',
    slug: 'san-marino',
    slug_locale_id: 'san-marino',
    denonym_slug: 'san-marino',
    denonym_slug_locale_id: 'san-marino'
  },
  {
    id: 191,
    name: 'Sao Tome and Principe',
    name_locale_id: 'Sao Tome dan Principe',
    dial_code: '239',
    iso2: 'ST',
    iso3: 'STP',
    denonym: 'Sao Tome and Principe',
    denonym_locale_id: 'Sao Tome dan Principe',
    slug: 'sao-tome-and-principe',
    slug_locale_id: 'sao-tome-dan-principe',
    denonym_slug: 'sao-tome-and-principe',
    denonym_slug_locale_id: 'sao-tome-dan-principe'
  },
  {
    id: 192,
    name: 'Saudi Arabia',
    name_locale_id: 'Arab Saudi',
    dial_code: '966',
    iso2: 'SA',
    iso3: 'SAU',
    denonym: 'Saudi Arabia',
    denonym_locale_id: 'Arab Saudi',
    slug: 'saudi-arabia',
    slug_locale_id: 'arab-saudi',
    denonym_slug: 'saudi-arabia',
    denonym_slug_locale_id: 'arab-saudi'
  },
  {
    id: 193,
    name: 'Senegal',
    name_locale_id: 'Senegal',
    dial_code: '221',
    iso2: 'SN',
    iso3: 'SEN',
    denonym: 'Senegal',
    denonym_locale_id: 'Senegal',
    slug: 'senegal',
    slug_locale_id: 'senegal',
    denonym_slug: 'senegal',
    denonym_slug_locale_id: 'senegal'
  },
  {
    id: 194,
    name: 'Serbia',
    name_locale_id: 'Serbia',
    dial_code: '381',
    iso2: 'RS',
    iso3: 'SRB',
    denonym: 'Serbia',
    denonym_locale_id: 'Serbia',
    slug: 'serbia',
    slug_locale_id: 'serbia',
    denonym_slug: 'serbia',
    denonym_slug_locale_id: 'serbia'
  },
  {
    id: 195,
    name: 'Seychelles',
    name_locale_id: 'Seychelles',
    dial_code: '248',
    iso2: 'SC',
    iso3: 'SYC',
    denonym: 'Seychelles',
    denonym_locale_id: 'Seychelles',
    slug: 'seychelles',
    slug_locale_id: 'seychelles',
    denonym_slug: 'seychelles',
    denonym_slug_locale_id: 'seychelles'
  },
  {
    id: 196,
    name: 'Sierra Leone',
    name_locale_id: 'Sierra Leone',
    dial_code: '232',
    iso2: 'SL',
    iso3: 'SLE',
    denonym: 'Sierra Leone',
    denonym_locale_id: 'Sierra Leone',
    slug: 'sierra-leone',
    slug_locale_id: 'sierra-leone',
    denonym_slug: 'sierra-leone',
    denonym_slug_locale_id: 'sierra-leone'
  },
  {
    id: 197,
    name: 'Singapore',
    name_locale_id: 'Singapura',
    dial_code: '65',
    iso2: 'SG',
    iso3: 'SGP',
    denonym: 'Singapore',
    denonym_locale_id: 'Singapura',
    slug: 'singapore',
    slug_locale_id: 'singapura',
    denonym_slug: 'singapore',
    denonym_slug_locale_id: 'singapura'
  },
  {
    id: 198,
    name: 'Sint Maarten (Dutch part)',
    name_locale_id: 'Sint Maarten (Bagian Belanda)',
    dial_code: '1-721',
    iso2: 'SX',
    iso3: 'SXM',
    denonym: 'Sint Maarten (Dutch part)',
    denonym_locale_id: 'Sint Maarten (Bagian Belanda)',
    slug: 'sint-maarten-dutch-part',
    slug_locale_id: 'sint-maarten-bagian-belanda',
    denonym_slug: 'sint-maarten-dutch-part',
    denonym_slug_locale_id: 'sint-maarten-bagian-belanda'
  },
  {
    id: 199,
    name: 'Slovakia',
    name_locale_id: 'Slovakia',
    dial_code: '421',
    iso2: 'SK',
    iso3: 'SVK',
    denonym: 'Slovakia',
    denonym_locale_id: 'Slovakia',
    slug: 'slovakia',
    slug_locale_id: 'slovakia',
    denonym_slug: 'slovakia',
    denonym_slug_locale_id: 'slovakia'
  },
  {
    id: 200,
    name: 'Slovenia',
    name_locale_id: 'Slovenia',
    dial_code: '386',
    iso2: 'SI',
    iso3: 'SVN',
    denonym: 'Slovenia',
    denonym_locale_id: 'Slovenia',
    slug: 'slovenia',
    slug_locale_id: 'slovenia',
    denonym_slug: 'slovenia',
    denonym_slug_locale_id: 'slovenia'
  },
  {
    id: 201,
    name: 'Solomon Islands',
    name_locale_id: 'Kepulauan Solomon',
    dial_code: '677',
    iso2: 'SB',
    iso3: 'SLB',
    denonym: 'Solomon Islands',
    denonym_locale_id: 'Kepulauan Solomon',
    slug: 'solomon-islands',
    slug_locale_id: 'kepulauan-solomon',
    denonym_slug: 'solomon-islands',
    denonym_slug_locale_id: 'kepulauan-solomon'
  },
  {
    id: 202,
    name: 'Somalia',
    name_locale_id: 'Somalia',
    dial_code: '252',
    iso2: 'SO',
    iso3: 'SOM',
    denonym: 'Somalia',
    denonym_locale_id: 'Somalia',
    slug: 'somalia',
    slug_locale_id: 'somalia',
    denonym_slug: 'somalia',
    denonym_slug_locale_id: 'somalia'
  },
  {
    id: 203,
    name: 'South Africa',
    name_locale_id: 'Afrika Selatan',
    dial_code: '27',
    iso2: 'ZA',
    iso3: 'ZAF',
    denonym: 'South Africa',
    denonym_locale_id: 'Afrika Selatan',
    slug: 'south-africa',
    slug_locale_id: 'afrika-selatan',
    denonym_slug: 'south-africa',
    denonym_slug_locale_id: 'afrika-selatan'
  },
  {
    id: 204,
    name: 'South Georgia and the South Sandwich Islands',
    name_locale_id: 'Kepulauan Georgia Selatan dan Sandwich Selatan',
    dial_code: '500',
    iso2: 'GS',
    iso3: 'SGS',
    denonym: 'South Georgia and the South Sandwich Islands',
    denonym_locale_id: 'Kepulauan Georgia Selatan dan Sandwich Selatan',
    slug: 'south-georgian-south-sandwich-islands',
    slug_locale_id: 'kepulauan-georgia-selatan-dan-sandwich-selatan',
    denonym_slug: 'south-georgian-south-sandwich-islands',
    denonym_slug_locale_id: 'kepulauan-georgia-selatan-dan-sandwich-selatan'
  },
  {
    id: 206,
    name: 'Spain',
    name_locale_id: 'Spanyol',
    dial_code: '34',
    iso2: 'ES',
    iso3: 'ESP',
    denonym: 'Spain',
    denonym_locale_id: 'Spanyol',
    slug: 'spain',
    slug_locale_id: 'spanyol',
    denonym_slug: 'spain',
    denonym_slug_locale_id: 'spanyol'
  },
  {
    id: 207,
    name: 'Sri Lanka',
    name_locale_id: 'Sri Lanka',
    dial_code: '94',
    iso2: 'LK',
    iso3: 'LKA',
    denonym: 'Sri Lanka',
    denonym_locale_id: 'Sri Lanka',
    slug: 'sri-lanka',
    slug_locale_id: 'sri-lanka',
    denonym_slug: 'sri-lanka',
    denonym_slug_locale_id: 'sri-lanka'
  },
  {
    id: 209,
    name: 'Sudan',
    name_locale_id: 'Sudan',
    dial_code: '249',
    iso2: 'SD',
    iso3: 'SDN',
    denonym: 'Sudan',
    denonym_locale_id: 'Sudan',
    slug: 'sudan',
    slug_locale_id: 'sudan',
    denonym_slug: 'sudan',
    denonym_slug_locale_id: 'sudan'
  },
  {
    id: 205,
    name: 'Sudan, South',
    name_locale_id: 'Sudan Selatan',
    dial_code: '211',
    iso2: 'SS',
    iso3: 'SSD',
    denonym: 'Sudan, South',
    denonym_locale_id: 'Sudan Selatan',
    slug: 'south-sudan',
    slug_locale_id: 'sudan-selatan',
    denonym_slug: 'south-sudan',
    denonym_slug_locale_id: 'sudan-selatan'
  },
  {
    id: 210,
    name: 'Suriname',
    name_locale_id: 'Suriname',
    dial_code: '597',
    iso2: 'SR',
    iso3: 'SUR',
    denonym: 'Suriname',
    denonym_locale_id: 'Suriname',
    slug: 'suriname',
    slug_locale_id: 'suriname',
    denonym_slug: 'suriname',
    denonym_slug_locale_id: 'suriname'
  },
  {
    id: 211,
    name: 'Svalbard and Jan Mayen Islands',
    name_locale_id: 'Kepulauan Svalbard dan Jan Mayen',
    dial_code: '47',
    iso2: 'SJ',
    iso3: 'SJM',
    denonym: 'Svalbard and Jan Mayen Islands',
    denonym_locale_id: 'Kepulauan Svalbard dan Jan Mayen',
    slug: 'svalbard-and-jan-mayen-islands',
    slug_locale_id: 'kepulauan-svalbard-dan-jan-mayen',
    denonym_slug: 'svalbard-and-jan-mayen-islands',
    denonym_slug_locale_id: 'kepulauan-svalbard-dan-jan-mayen'
  },
  {
    id: 212,
    name: 'Sweden',
    name_locale_id: 'Swedia',
    dial_code: '46',
    iso2: 'SE',
    iso3: 'SWE',
    denonym: 'Sweden',
    denonym_locale_id: 'Swedia',
    slug: 'sweden',
    slug_locale_id: 'swedia',
    denonym_slug: 'sweden',
    denonym_slug_locale_id: 'swedia'
  },
  {
    id: 213,
    name: 'Switzerland',
    name_locale_id: 'Swiss',
    dial_code: '41',
    iso2: 'CH',
    iso3: 'CHE',
    denonym: 'Switzerland',
    denonym_locale_id: 'Swiss',
    slug: 'switzerland',
    slug_locale_id: 'swiss',
    denonym_slug: 'switzerland',
    denonym_slug_locale_id: 'swiss'
  },
  {
    id: 214,
    name: 'Syria',
    name_locale_id: 'Suriah',
    dial_code: '963',
    iso2: 'SY',
    iso3: 'SYR',
    denonym: 'Syria',
    denonym_locale_id: 'Suriah',
    slug: 'syria',
    slug_locale_id: 'suriah',
    denonym_slug: 'syria',
    denonym_slug_locale_id: 'suriah'
  },
  {
    id: 249,
    name: 'Taiwan',
    name_locale_id: 'Taiwan',
    dial_code: '886',
    iso2: 'TW',
    iso3: 'TWN',
    denonym: 'Taiwan',
    denonym_locale_id: 'Taiwan',
    slug: 'taiwan',
    slug_locale_id: 'taiwan',
    denonym_slug: 'taiwan',
    denonym_slug_locale_id: 'taiwan'
  },
  {
    id: 215,
    name: 'Tajikistan',
    name_locale_id: 'Tajikistan',
    dial_code: '992',
    iso2: 'TJ',
    iso3: 'TJK',
    denonym: 'Tajikistan',
    denonym_locale_id: 'Tajikistan',
    slug: 'tajikistan',
    slug_locale_id: 'tajikistan',
    denonym_slug: 'tajikistan',
    denonym_slug_locale_id: 'tajikistan'
  },
  {
    id: 232,
    name: 'Tanzania',
    name_locale_id: 'Tanzania',
    dial_code: '255',
    iso2: 'TZ',
    iso3: 'TZA',
    denonym: 'Tanzania',
    denonym_locale_id: 'Tanzania',
    slug: 'tanzania',
    slug_locale_id: 'tanzania',
    denonym_slug: 'tanzania',
    denonym_slug_locale_id: 'tanzania'
  },
  {
    id: 216,
    name: 'Thailand',
    name_locale_id: 'Thailand',
    dial_code: '66',
    iso2: 'TH',
    iso3: 'THA',
    denonym: 'Thailand',
    denonym_locale_id: 'Thailand',
    slug: 'thailand',
    slug_locale_id: 'thailand',
    denonym_slug: 'thailand',
    denonym_slug_locale_id: 'thailand'
  },
  {
    id: 15,
    name: 'The Bahamas',
    name_locale_id: 'Bahama',
    dial_code: '1-242',
    iso2: 'BS',
    iso3: 'BHS',
    denonym: 'The Bahamas',
    denonym_locale_id: 'Bahama',
    slug: 'the-bahamas',
    slug_locale_id: 'bahama',
    denonym_slug: 'the-bahamas',
    denonym_slug_locale_id: 'bahama'
  },
  {
    id: 83,
    name: 'The Gambia',
    name_locale_id: 'Gambia',
    dial_code: '220',
    iso2: 'GM',
    iso3: 'GMB',
    denonym: 'The Gambia',
    denonym_locale_id: 'Gambia',
    slug: 'the-gambia',
    slug_locale_id: 'gambia',
    denonym_slug: 'the-gambia',
    denonym_slug_locale_id: 'gambia'
  },
  {
    id: 219,
    name: 'Togo',
    name_locale_id: 'Togo',
    dial_code: '228',
    iso2: 'TG',
    iso3: 'TGO',
    denonym: 'Togo',
    denonym_locale_id: 'Togo',
    slug: 'togo',
    slug_locale_id: 'togo',
    denonym_slug: 'togo',
    denonym_slug_locale_id: 'togo'
  },
  {
    id: 220,
    name: 'Tokelau',
    name_locale_id: 'Tokelau',
    dial_code: '690',
    iso2: 'TK',
    iso3: 'TKL',
    denonym: 'Tokelau',
    denonym_locale_id: 'Tokelau',
    slug: 'tokelau',
    slug_locale_id: 'tokelau',
    denonym_slug: 'tokelau',
    denonym_slug_locale_id: 'tokelau'
  },
  {
    id: 221,
    name: 'Tonga',
    name_locale_id: 'Tonga',
    dial_code: '676',
    iso2: 'TO',
    iso3: 'TON',
    denonym: 'Tonga',
    denonym_locale_id: 'Tonga',
    slug: 'tonga',
    slug_locale_id: 'tonga',
    denonym_slug: 'tonga',
    denonym_slug_locale_id: 'tonga'
  },
  {
    id: 222,
    name: 'Trinidad and Tobago',
    name_locale_id: 'Trinidad dan Tobago',
    dial_code: '1-868',
    iso2: 'TT',
    iso3: 'TTO',
    denonym: 'Trinidad and Tobago',
    denonym_locale_id: 'Trinidad dan Tobago',
    slug: 'trinidad-and-tobago',
    slug_locale_id: 'trinidad-dan-tobago',
    denonym_slug: 'trinidad-and-tobago',
    denonym_slug_locale_id: 'trinidad-dan-tobago'
  },
  {
    id: 223,
    name: 'Tunisia',
    name_locale_id: 'Tunisia',
    dial_code: '216',
    iso2: 'TN',
    iso3: 'TUN',
    denonym: 'Tunisia',
    denonym_locale_id: 'Tunisia',
    slug: 'tunisia',
    slug_locale_id: 'tunisia',
    denonym_slug: 'tunisia',
    denonym_slug_locale_id: 'tunisia'
  },
  {
    id: 224,
    name: 'Turkey',
    name_locale_id: 'Turki',
    dial_code: '90',
    iso2: 'TR',
    iso3: 'TUR',
    denonym: 'Turkey',
    denonym_locale_id: 'Turki',
    slug: 'turkey',
    slug_locale_id: 'turki',
    denonym_slug: 'turkey',
    denonym_slug_locale_id: 'turki'
  },
  {
    id: 225,
    name: 'Turkmenistan',
    name_locale_id: 'Turkmenistan',
    dial_code: '993',
    iso2: 'TM',
    iso3: 'TKM',
    denonym: 'Turkmenistan',
    denonym_locale_id: 'Turkmenistan',
    slug: 'turkmenistan',
    slug_locale_id: 'turkmenistan',
    denonym_slug: 'turkmenistan',
    denonym_slug_locale_id: 'turkmenistan'
  },
  {
    id: 226,
    name: 'Turks and Caicos Islands',
    name_locale_id: 'Kepulauan Turks dan Caicos',
    dial_code: '1-649',
    iso2: 'TC',
    iso3: 'TCA',
    denonym: 'Turks and Caicos Islands',
    denonym_locale_id: 'Kepulauan Turks dan Caicos',
    slug: 'turks-and-caicos-islands',
    slug_locale_id: 'kepulauan-turks-dan-caicos',
    denonym_slug: 'turks-and-caicos-islands',
    denonym_slug_locale_id: 'kepulauan-turks-dan-caicos'
  },
  {
    id: 227,
    name: 'Tuvalu',
    name_locale_id: 'Tuvalu',
    dial_code: '688',
    iso2: 'TV',
    iso3: 'TUV',
    denonym: 'Tuvalu',
    denonym_locale_id: 'Tuvalu',
    slug: 'tuvalu',
    slug_locale_id: 'tuvalu',
    denonym_slug: 'tuvalu',
    denonym_slug_locale_id: 'tuvalu'
  },
  {
    id: 228,
    name: 'Uganda',
    name_locale_id: 'Uganda',
    dial_code: '256',
    iso2: 'UG',
    iso3: 'UGA',
    denonym: 'Uganda',
    denonym_locale_id: 'Uganda',
    slug: 'uganda',
    slug_locale_id: 'uganda',
    denonym_slug: 'uganda',
    denonym_slug_locale_id: 'uganda'
  },
  {
    id: 229,
    name: 'Ukraine',
    name_locale_id: 'Ukraina',
    dial_code: '380',
    iso2: 'UA',
    iso3: 'UKR',
    denonym: 'Ukraine',
    denonym_locale_id: 'Ukraina',
    slug: 'ukraine',
    slug_locale_id: 'ukraina',
    denonym_slug: 'ukraine',
    denonym_slug_locale_id: 'ukraina'
  },
  {
    id: 230,
    name: 'United Arab Emirates',
    name_locale_id: 'Uni Emirat Arab',
    dial_code: '971',
    iso2: 'AE',
    iso3: 'ARE',
    denonym: 'United Arab Emirates',
    denonym_locale_id: 'Uni Emirat Arab',
    slug: 'united-arab-emirates',
    slug_locale_id: 'uni-emirat-arab',
    denonym_slug: 'united-arab-emirates',
    denonym_slug_locale_id: 'uni-emirat-arab'
  },
  {
    id: 231,
    name: 'United Kingdom',
    name_locale_id: 'Inggris',
    dial_code: '44',
    iso2: 'GB',
    iso3: 'GBR',
    denonym: 'United Kingdom',
    denonym_locale_id: 'Inggris',
    slug: 'united-kingdom',
    slug_locale_id: 'inggris',
    denonym_slug: 'united-kingdom',
    denonym_slug_locale_id: 'inggris'
  },
  {
    id: 234,
    name: 'United States',
    name_locale_id: 'Amerika Serikat',
    dial_code: '1',
    iso2: 'US',
    iso3: 'USA',
    denonym: 'United States',
    denonym_locale_id: 'Amerika Serikat',
    slug: 'united-states',
    slug_locale_id: 'amerika-serikat',
    denonym_slug: 'united-states',
    denonym_slug_locale_id: 'amerika-serikat'
  },
  {
    id: 233,
    name: 'United States Virgin Islands',
    name_locale_id: 'Kepulauan Virgin Amerika Serikat',
    dial_code: '1-340',
    iso2: 'VI',
    iso3: 'VIR',
    denonym: 'United States Virgin Islands',
    denonym_locale_id: 'Kepulauan Virgin Amerika Serikat',
    slug: 'united-states-virgin-islands',
    slug_locale_id: 'kepulauan-virgin-amerika-serikat',
    denonym_slug: 'united-states-virgin-islands',
    denonym_slug_locale_id: 'kepulauan-virgin-amerika-serikat'
  },
  {
    id: 235,
    name: 'Uruguay',
    name_locale_id: 'Uruguay',
    dial_code: '598',
    iso2: 'UY',
    iso3: 'URY',
    denonym: 'Uruguay',
    denonym_locale_id: 'Uruguay',
    slug: 'uruguay',
    slug_locale_id: 'uruguay',
    denonym_slug: 'uruguay',
    denonym_slug_locale_id: 'uruguay'
  },
  {
    id: 236,
    name: 'Uzbekistan',
    name_locale_id: 'Uzbekistan',
    dial_code: '998',
    iso2: 'UZ',
    iso3: 'UZB',
    denonym: 'Uzbekistan',
    denonym_locale_id: 'Uzbekistan',
    slug: 'uzbekistan',
    slug_locale_id: 'uzbekistan',
    denonym_slug: 'uzbekistan',
    denonym_slug_locale_id: 'uzbekistan'
  },
  {
    id: 237,
    name: 'Vanuatu',
    name_locale_id: 'Vanuatu',
    dial_code: '678',
    iso2: 'VU',
    iso3: 'VUT',
    denonym: 'Vanuatu',
    denonym_locale_id: 'Vanuatu',
    slug: 'vanuatu',
    slug_locale_id: 'vanuatu',
    denonym_slug: 'vanuatu',
    denonym_slug_locale_id: 'vanuatu'
  },
  {
    id: 100,
    name: 'Vatican City',
    name_locale_id: 'Vatikan',
    dial_code: '39-06',
    iso2: 'VA',
    iso3: 'VAT',
    denonym: 'Vatican City',
    denonym_locale_id: 'Vatikan',
    slug: 'vatican-city',
    slug_locale_id: 'vatikan',
    denonym_slug: 'vatican-city',
    denonym_slug_locale_id: 'vatikan'
  },
  {
    id: 238,
    name: 'Venezuela',
    name_locale_id: 'Venezuela',
    dial_code: '58',
    iso2: 'VE',
    iso3: 'VEN',
    denonym: 'Venezuela',
    denonym_locale_id: 'Venezuela',
    slug: 'venezuela',
    slug_locale_id: 'venezuela',
    denonym_slug: 'venezuela',
    denonym_slug_locale_id: 'venezuela'
  },
  {
    id: 239,
    name: 'Vietnam',
    name_locale_id: 'Vietnam',
    dial_code: '84',
    iso2: 'VN',
    iso3: 'VNM',
    denonym: 'Vietnam',
    denonym_locale_id: 'Vietnam',
    slug: 'vietnam',
    slug_locale_id: 'vietnam',
    denonym_slug: 'vietnam',
    denonym_slug_locale_id: 'vietnam'
  },
  {
    id: 240,
    name: 'Wallis and Futuna Islands',
    name_locale_id: 'Kepulauan Wallis dan Futuna',
    dial_code: '681',
    iso2: 'WF',
    iso3: 'WLF',
    denonym: 'Wallis and Futuna Islands',
    denonym_locale_id: 'Kepulauan Wallis dan Futuna',
    slug: 'wallis-and-futuna-islands',
    slug_locale_id: 'kepulauan-wallis-dan-futuna',
    denonym_slug: 'wallis-and-futuna-islands',
    denonym_slug_locale_id: 'kepulauan-wallis-dan-futuna'
  },
  {
    id: 241,
    name: 'Western Sahara',
    name_locale_id: 'Sahara Barat',
    dial_code: '212',
    iso2: 'EH',
    iso3: 'ESH',
    denonym: 'Western Sahara',
    denonym_locale_id: 'Sahara Barat',
    slug: 'western-sahara',
    slug_locale_id: 'sahara-barat',
    denonym_slug: 'western-sahara',
    denonym_slug_locale_id: 'sahara-barat'
  },
  {
    id: 242,
    name: 'Yemen',
    name_locale_id: 'Yaman',
    dial_code: '967',
    iso2: 'YE',
    iso3: 'YEM',
    denonym: 'Yemen',
    denonym_locale_id: 'Yaman',
    slug: 'yemen',
    slug_locale_id: 'yaman',
    denonym_slug: 'yemen',
    denonym_slug_locale_id: 'yaman'
  },
  {
    id: 243,
    name: 'Zambia',
    name_locale_id: 'Zambia',
    dial_code: '260',
    iso2: 'ZM',
    iso3: 'ZMB',
    denonym: 'Zambia',
    denonym_locale_id: 'Zambia',
    slug: 'zambia',
    slug_locale_id: 'zambia',
    denonym_slug: 'zambia',
    denonym_slug_locale_id: 'zambia'
  },
  {
    id: 244,
    name: 'Zimbabwe',
    name_locale_id: 'Zimbabwe',
    dial_code: '263',
    iso2: 'ZW',
    iso3: 'ZWE',
    denonym: 'Zimbabwe',
    denonym_locale_id: 'Zimbabwe',
    slug: 'zimbabwe',
    slug_locale_id: 'zimbabwe',
    denonym_slug: 'zimbabwe',
    denonym_slug_locale_id: 'zimbabwe'
  }
];

// export default function Home() {
//   /*
//     input: from-indonesia-to-hongkong
//     output: f105, t102

//     input: to-hongkong-from-indonesia
//     output: f105, t102

//     input: from-south-korea
//     output: f176

//     input: to-south-korea
//     output: t176

//     input: from-south-korea-to-saint-lucia
//     output: f176, t185
//   */

//   const handleDisplayOutput = (text: string) => {
//     /* function here */
//     return text
//   }

//   return (
//     <div className="flex flex-col items-center justify-center pt-20 gap-10">
//       <div className="text-7xl font-bold">Hello from SPUN</div>

//       <div className="flex flex-col gap-5">
//         <div>{handleDisplayOutput('test')}</div>
//         <div>Place your code below after here</div>
//       </div>
//     </div>
//   );
// }

function lmao(input) {
  const slugToId = Object.fromEntries(
    country.map(({ slug, id }) => [slug, id])
  );

  // Extract slugs from the input string using regex
  // const slugs = input.split('-').filter(part => slugToId[part]);

  // const slugs = input.split('-').map(part => {
  //   if (part === 'from') {
  //     return 'f'; // Replace 'from' with 'f'
  //   } else if (part === 'to') {
  //     return 't'; // Replace 'to' with 't'
  //   } else {
  //     return slugToId[part]; // Keep valid slugs or null if not found
  //   }
  // })
  // Filter out null values
  // const slugs = input.split('-').filter(part => {
  //   if (part === 'from' || part === 'to') {
  //     return 'from'; // Ignore 'from' and 'to'
  //   }
  //   return slugToId[part]; // Keep only valid slugs
  // });

  // Map slugs to ids and format the result with "f" for from and "t" for to
  // return slugs.map((slug, index) => {
  //   return (index === 0 ? 'f' : 't') + slugToId[slug];
  // }).join(', ');

  const mappingSlug = input.split('-').map(part => {
    if (part === 'from') {
      return 'f';
    } else if (part === 'to') {
      return 't';
    } else {
      return part;
    }
  });

  // const mappingCountry = mappingSlug.map(part => {
  //   if (part === 'f' || part === 't') {
  //     return part
  //   } else {
  //     return slugToId[part]
  //   }
  // })

  // const mappingCountry = mappingSlug.reduce((part1, part2) => {
  //   return `${part1}-${part2}`
  // })

  function transformArray(arr) {
    const result = [];
    let i = 0;

    while (i < arr.length) {
      const prefix = arr[i]; // 'f' or 't'
      i++;

      const group = [];
      while (i < arr.length && arr[i] !== 'f' && arr[i] !== 't') {
        group.push(arr[i]);
        i++;
      }

      result.push(`${prefix} ${group.join('-')}`);
    }

    return result.join(' ');
  }

  // return transformArray(mappingSlug);
}

// console.log(lmao('from-south-korea'));
// console.log(lmao('from-indonesia-to-hongkong'));
// console.log(lmao('from-south-korea-to-saint-lucia'));
// console.log(lmao('to-south-korea'));
// console.log(lmao('to-hongkong-from-indonesia'));


function mapC() {
  country.forEach((item) => {
    console.log(item.denonym)
  })
}

mapC()